#! /bin/sh 
set -e

# Written by Jim Van Zandt <jrv@vanzandt.mv.com>, borrowing heavily
# from the install scripts for gettext by Santiago Vila
# <sanvila@ctv.es> and octave by Dirk Eddelbuettel <edd@debian.org>.

FLAVOR=$1
PACKAGE=ilisp

if [ ${FLAVOR} = emacs ]; then exit 0; fi

echo install/${PACKAGE}: Handling install for emacsen flavor ${FLAVOR}

HYPERSPEC=hyperspec.el

#FLAVORTEST=`echo $FLAVOR | cut -c-6`
#if [ ${FLAVORTEST} = xemacs ] ; then
#    SITEFLAG="-no-site-file"
#else
#    SITEFLAG="--no-site-file"
#fi

FLAGS="${SITEFLAG} -q -batch -l path.el"

ELDIR=/usr/share/emacs/site-lisp/${PACKAGE}
ELCDIR=/usr/share/${FLAVOR}/site-lisp/${PACKAGE}

# Install-info-altdir does not actually exist. 
# Maybe somebody will write it.
if test -x /usr/sbin/install-info-altdir; then
    echo install/${PACKAGE}: install Info links for ${FLAVOR}
    install-info-altdir --quiet --section "" "" --dirname=${FLAVOR} /usr/info/${PACKAGE}.info.gz
fi

install -m 755 -d ${ELCDIR}
install -m 755 -d ${ELCDIR}/extra
cd ${ELDIR}
cp `echo *.el` ${ELCDIR}
cd ${ELDIR}/extra
cp ${HYPERSPEC} ${ELCDIR}/extra/hyperspec.el
cp cltl2.el ${ELCDIR}/extra/cltl2.el

cd ${ELCDIR}

LOG=`tempfile`;
trap "test -f $LOG && mv -f $LOG  $ELCDIR/install.log > /dev/null 2>&1 && chmod 644 $ELCDIR/install.log" exit

cat << EOF > path.el
(setq load-path (cons "." load-path) byte-compile-warnings nil)
(load "ilisp-mak.el")
EOF
${FLAVOR} ${FLAGS}     >> $LOG  2>&1;

# Don't remove .el files since ilisp-mak.el does not compile all files
# rm -f *.el path.el extra/*.el

exit 0
