(defun color-theme-sugarshark ()
  "Color theme by Ole Arndt, created 2006-03-05."
  (interactive)
  (color-theme-install
   '(color-theme-sugarshark
     ((background-color . "#537182")
      (background-mode . dark)
      (background-toolbar-color . "#cf3ccf3ccf3c")
      (border-color . "black")
      (bottom-toolbar-shadow-color . "#79e77df779e7")
      (cursor-color . "LightGray")
      (foreground-color . "AntiqueWhite2")
      (mouse-color . "Grey")
      (top-toolbar-shadow-color . "#fffffbeeffff")
      (viper-saved-cursor-color-in-replace-mode . "Red3"))
     ((apropos-keybinding-face . underline)
      (apropos-label-face . italic)
      (apropos-match-face . secondary-selection)
      (apropos-property-face . bold-italic)
      (apropos-symbol-face . bold)
      (cua-global-mark-cursor-color . "cyan")
      (cua-normal-cursor-color . "LightGray")
      (cua-overwrite-cursor-color . "yellow")
      (cua-read-only-cursor-color . "darkgreen")
      (cvs-conflict-current-face . cvs-conflict-current-face)
      (cvs-conflict-separater-face . cvs-conflict-separater-face)
      (cvs-conflict-update-face . cvs-conflict-update-face)
      (ecb-analyse-bucket-element-face . ecb-analyse-bucket-element-face)
      (ecb-analyse-bucket-node-face . ecb-analyse-bucket-node-face)
      (ecb-analyse-face . ecb-default-highlight-face)
      (ecb-analyse-general-face . ecb-default-general-face)
      (ecb-directories-general-face . ecb-default-general-face)
      (ecb-directory-face . ecb-default-highlight-face)
      (ecb-directory-not-accessible-face . ecb-directory-not-accessible-face)
      (ecb-history-face . ecb-default-highlight-face)
      (ecb-history-general-face . ecb-default-general-face)
      (ecb-method-face . ecb-default-highlight-face)
      (ecb-method-non-semantic-face . speedbar-tag-face)
      (ecb-methods-general-face . ecb-default-general-face)
      (ecb-mode-line-data-face . ecb-mode-line-data-face)
      (ecb-mode-line-prefix-face . ecb-mode-line-prefix-face)
      (ecb-mode-line-win-nr-face . ecb-mode-line-win-nr-face)
      (ecb-source-face . ecb-default-highlight-face)
      (ecb-source-in-directories-buffer-face . ecb-sources-face)
      (ecb-source-read-only-face . ecb-source-read-only-face)
      (ecb-sources-general-face . ecb-default-general-face)
      (ecb-tag-header-face . ecb-tag-header-face)
      (ecb-tree-guide-line-face . ecb-tree-guide-line-face)
      (gnus-article-button-face . bold)
      (gnus-article-mouse-face . highlight)
      (gnus-mouse-face . highlight)
      (gnus-signature-face . gnus-signature)
      (gnus-summary-selected-face . gnus-summary-selected)
      (gnus-treat-display-face . head)
      (ispell-highlight-face . highlight)
      (list-matching-lines-buffer-name-face . underline)
      (list-matching-lines-face . bold)
      (paren-match-face . paren-face-match)
      (paren-mismatch-face . paren-face-mismatch)
      (paren-no-match-face . paren-face-no-match)
      (semantic-which-function-use-color . t)
      (spam-face . spam)
      (tags-tag-face . default)
      (view-highlight-face . highlight)
      (widget-mouse-face . highlight))
     (default ((t (:stipple nil :background "#537182" :foreground "AntiqueWhite2" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 103 :width normal :family "misc-fixed"))))
     (bbdb-company ((t (:italic t :slant italic))))
     (bbdb-field-name ((t (:bold t :foreground "MediumAquamarine" :weight bold))))
     (bbdb-field-value ((t (nil))))
     (bbdb-name ((t (:underline t))))
     (bg:erc-color-face0 ((t (:background "White"))))
     (bg:erc-color-face1 ((t (:background "black"))))
     (bg:erc-color-face10 ((t (:background "lightblue1"))))
     (bg:erc-color-face11 ((t (:background "cyan"))))
     (bg:erc-color-face12 ((t (:background "blue"))))
     (bg:erc-color-face13 ((t (:background "deeppink"))))
     (bg:erc-color-face14 ((t (:background "gray50"))))
     (bg:erc-color-face15 ((t (:background "gray90"))))
     (bg:erc-color-face2 ((t (:background "blue4"))))
     (bg:erc-color-face3 ((t (:background "green4"))))
     (bg:erc-color-face4 ((t (:background "red"))))
     (bg:erc-color-face5 ((t (:background "brown"))))
     (bg:erc-color-face6 ((t (:background "purple"))))
     (bg:erc-color-face7 ((t (:background "orange"))))
     (bg:erc-color-face8 ((t (:background "yellow"))))
     (bg:erc-color-face9 ((t (:background "green"))))
     (blank-space-face ((t (:background "LightGray"))))
     (blank-tab-face ((t (:background "Wheat" :foreground "DarkSlateGray"))))
     (blue ((t (:foreground "SkyBlue"))))
     (bold ((t (:bold t :foreground "LightBlue" :weight bold))))
     (bold-italic ((t (:italic t :bold t :foreground "SkyBlue" :slant italic :weight bold))))
     (bookmark-menu-heading ((t (:bold t :weight bold :foreground "OliveDrab3"))))
     (border ((t (:background "black"))))
     (border-glyph ((t (nil))))
     (buffer-menu-buffer ((t (:bold t :weight bold))))
     (buffers-tab ((t (:background "black" :foreground "LightSkyBlue"))))
     (button ((t (:underline t))))
     (calendar-today ((t (:underline t))))
     (change-log-acknowledgement-face ((t (:foreground "LightBlue"))))
     (change-log-conditionals-face ((t (:bold t :foreground "Aquamarine" :weight bold))))
     (change-log-date-face ((t (:foreground "LightSalmon"))))
     (change-log-email-face ((t (:bold t :foreground "Aquamarine" :weight bold))))
     (change-log-file-face ((t (:bold t :foreground "Aquamarine" :weight bold))))
     (change-log-function-face ((t (:bold t :foreground "Aquamarine" :weight bold))))
     (change-log-list-face ((t (:foreground "Salmon"))))
     (change-log-name-face ((t (:foreground "Aquamarine"))))
     (color-color-face ((t (:bold t :background "ForestGreen" :weight bold))))
     (comint-highlight-input ((t (:bold t :weight bold))))
     (comint-highlight-prompt ((t (:foreground "cyan"))))
     (comint-input-face ((t (:foreground "deepskyblue"))))
     (compilation-column-number ((t (:bold t :weight bold :foreground "OliveDrab3"))))
     (compilation-error ((t (:bold t :weight bold :foreground "LightSalmon"))))
     (compilation-info ((t (:bold t :foreground "Green1" :weight bold))))
     (compilation-line-number ((t (:bold t :weight bold :foreground "LightBlue"))))
     (compilation-warning ((t (:bold t :foreground "Orange" :weight bold))))
     (completions-common-part ((t (:family "misc-fixed" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "AntiqueWhite2" :background "#537182" :stipple nil :height 103))))
     (completions-first-difference ((t (:bold t :weight bold :foreground "MediumAquamarine"))))
     (cperl-array-face ((t (:bold t :foreground "Yellow" :weight bold))))
     (cperl-hash-face ((t (:bold t :foreground "White" :weight bold))))
     (cperl-invalid-face ((t (:foreground "white"))))
     (cperl-nonoverridable-face ((t (:foreground "SkyBlue"))))
     (cua-global-mark ((t (:background "yellow1" :foreground "black"))))
     (cua-rectangle ((t (:background "maroon" :foreground "white"))))
     (cua-rectangle-noselect ((t (:background "dimgray" :foreground "white"))))
     (cursor ((t (:background "LightGray"))))
     (custom-button ((t (:bold t :foreground "DarkSeaGreen2" :underline t :weight bold))))
     (custom-button-mouse ((t (:bold t :foreground "DarkSeaGreen1" :underline t :weight bold))))
     (custom-button-pressed ((t (:background "lightgrey" :foreground "black"))))
     (custom-button-pressed-unraised ((t (:underline t :foreground "violet"))))
     (custom-button-unraised ((t (:underline t))))
     (custom-changed ((t (:background "blue" :foreground "white"))))
     (custom-comment ((t (:background "AntiqueWhite4"))))
     (custom-comment-tag ((t (:foreground "AntiqueWhite4"))))
     (custom-documentation ((t (:foreground "Grey"))))
     (custom-face-tag ((t (:bold t :weight bold))))
     (custom-group-tag ((t (:bold t :foreground "LightBlue" :weight bold))))
     (custom-group-tag-1 ((t (:foreground "LightBlue"))))
     (custom-invalid ((t (:background "red" :foreground "yellow"))))
     (custom-link ((t (:bold t :underline t :foreground "LightBlue" :weight bold))))
     (custom-modified ((t (:background "blue" :foreground "white"))))
     (custom-rogue ((t (:background "black" :foreground "pink"))))
     (custom-saved ((t (:underline t))))
     (custom-set ((t (:background "white" :foreground "blue"))))
     (custom-state ((t (:foreground "DarkSeaGreen2"))))
     (custom-themed ((t (:background "blue1" :foreground "white"))))
     (custom-variable-button ((t (:bold t :underline t :weight bold))))
     (custom-variable-tag ((t (:bold t :weight bold))))
     (cvs-conflict-current-face ((t (:background "PaleGreen" :foreground "Black"))))
     (cvs-conflict-separater-face ((t (:background "Grey" :foreground "Black"))))
     (cvs-conflict-update-face ((t (:background "Wheat" :foreground "Black"))))
     (cvs-filename-face ((t (:foreground "blue4"))))
     (cvs-handled-face ((t (:foreground "pink"))))
     (cvs-header-face ((t (:bold t :foreground "blue4" :weight bold))))
     (cvs-marked-face ((t (:bold t :foreground "green3" :weight bold))))
     (cvs-msg-face ((t (:bold t :weight bold))))
     (cvs-need-action-face ((t (:foreground "orange"))))
     (cvs-unknown-face ((t (:foreground "red"))))
     (cyan ((t (:foreground "cyan"))))
     (darcsum-change-line-face ((t (:background "grey25" :foreground "grey75"))))
     (darcsum-filename-face ((t (:foreground "lightblue"))))
     (darcsum-header-face ((t (:bold t :foreground "lightyellow" :weight bold))))
     (darcsum-marked-face ((t (:bold t :weight bold))))
     (darcsum-need-action-face ((t (:foreground "orange"))))
     (darcsum-need-action-marked-face ((t (:bold t :foreground "orange" :weight bold))))
     (diary ((t (:bold t :foreground "cyan" :weight bold))))
     (diary-button ((t (nil))))
     (diff-added-face ((t (nil))))
     (diff-changed-face ((t (nil))))
     (diff-context-face ((t (:foreground "grey70"))))
     (diff-file-header-face ((t (:bold t :weight bold))))
     (diff-function-face ((t (:foreground "grey70"))))
     (diff-header-face ((t (:foreground "light salmon"))))
     (diff-hunk-header-face ((t (:foreground "light salmon"))))
     (diff-index-face ((t (:bold t :weight bold))))
     (diff-nonexistent-face ((t (:bold t :weight bold))))
     (diff-removed-face ((t (nil))))
     (dired-directory ((t (:bold t :weight bold :foreground "LightSalmon"))))
     (dired-face-boring ((t (:foreground "Gray65"))))
     (dired-face-directory ((t (:bold t :foreground "sky blue" :weight bold))))
     (dired-face-executable ((t (:foreground "green yellow"))))
     (dired-face-flagged ((t (:foreground "tomato"))))
     (dired-face-header ((t (:background "grey75" :foreground "black"))))
     (dired-face-marked ((t (:foreground "PaleTurquoise"))))
     (dired-face-permissions ((t (:foreground "aquamarine"))))
     (dired-face-setuid ((t (:foreground "Red"))))
     (dired-face-socket ((t (:foreground "magenta"))))
     (dired-face-symlink ((t (:foreground "gray95"))))
     (dired-flagged ((t (:bold t :weight bold :foreground "tomato"))))
     (dired-header ((t (:bold t :weight bold :foreground "OliveDrab3"))))
     (dired-ignored ((t (:foreground "grey70"))))
     (dired-mark ((t (:foreground "LightBlue"))))
     (dired-marked ((t (:bold t :weight bold :foreground "PaleTurquoise"))))
     (dired-symlink ((t (:bold t :weight bold :foreground "LightBlue"))))
     (dired-warning ((t (:foreground "Gray80"))))
     (display-time-mail-balloon-enhance-face ((t (:background "orange"))))
     (display-time-mail-balloon-gnus-group-face ((t (:foreground "blue"))))
     (display-time-time-balloon-face ((t (:foreground "red"))))
     (ecb-analyse-bucket-element-face ((t (nil))))
     (ecb-analyse-bucket-node-face ((t (:bold t :weight bold))))
     (ecb-analyse-face ((t (:background "magenta"))))
     (ecb-analyse-general-face ((t (:height 1.0))))
     (ecb-bucket-node-face ((t (:bold t :weight bold))))
     (ecb-default-general-face ((t (nil))))
     (ecb-default-highlight-face ((t (:foreground "LightSalmon" :weight bold))))
     (ecb-directories-general-face ((t (:height 1.0))))
     (ecb-directory-face ((t (:background "magenta"))))
     (ecb-directory-not-accessible-face ((t (:foreground "gray60"))))
     (ecb-history-face ((t (:background "magenta"))))
     (ecb-history-general-face ((t (:height 1.0))))
     (ecb-method-face ((t (:background "magenta"))))
     (ecb-method-non-semantic-face ((t (:foreground "brown" :height 1.0))))
     (ecb-methods-general-face ((t (:height 1.0))))
     (ecb-mode-line-data-face ((t (nil))))
     (ecb-mode-line-prefix-face ((t (:foreground "forestgreen"))))
     (ecb-mode-line-win-nr-face ((t (:bold t :weight bold))))
     (ecb-source-face ((t (:background "magenta"))))
     (ecb-source-in-directories-buffer-face ((t (:foreground "LightBlue1"))))
     (ecb-source-read-only-face ((t (:italic t :slant italic))))
     (ecb-sources-face ((t (:foreground "LightBlue1"))))
     (ecb-sources-general-face ((t (nil))))
     (ecb-tag-header-face ((t (:background "SeaGreen1"))))
     (ecb-tree-guide-line-face ((t (:foreground "gray" :height 1.0))))
     (ecb-type-tag-class-face ((t (:bold t :weight bold))))
     (ecb-type-tag-enum-face ((t (:bold t :weight bold))))
     (ecb-type-tag-group-face ((t (:bold t :foreground "dim gray" :weight bold))))
     (ecb-type-tag-interface-face ((t (:bold t :weight bold))))
     (ecb-type-tag-struct-face ((t (:bold t :weight bold))))
     (ecb-type-tag-typedef-face ((t (:bold t :weight bold))))
     (ecb-type-tag-union-face ((t (:bold t :weight bold))))
     (ediff-current-diff-face-A ((t (:background "pale green" :foreground "firebrick"))))
     (ediff-current-diff-face-Ancestor ((t (:background "VioletRed" :foreground "Black"))))
     (ediff-current-diff-face-B ((t (:background "Yellow" :foreground "DarkOrchid"))))
     (ediff-current-diff-face-C ((t (:background "indianred" :foreground "white"))))
     (ediff-even-diff-face-A ((t (:background "light gray" :foreground "Black"))))
     (ediff-even-diff-face-Ancestor ((t (:background "Gray" :foreground "White"))))
     (ediff-even-diff-face-B ((t (:background "Gray" :foreground "White"))))
     (ediff-even-diff-face-C ((t (:background "light gray" :foreground "Black"))))
     (ediff-fine-diff-face-A ((t (:background "sky blue" :foreground "Navy"))))
     (ediff-fine-diff-face-Ancestor ((t (:background "Green" :foreground "Black"))))
     (ediff-fine-diff-face-B ((t (:background "cyan" :foreground "Black"))))
     (ediff-fine-diff-face-C ((t (:background "Turquoise" :foreground "Black"))))
     (ediff-odd-diff-face-A ((t (:background "Gray" :foreground "White"))))
     (ediff-odd-diff-face-Ancestor ((t (:background "light gray" :foreground "Black"))))
     (ediff-odd-diff-face-B ((t (:background "light gray" :foreground "Black"))))
     (ediff-odd-diff-face-C ((t (:background "Gray" :foreground "White"))))
     (eieio-custom-slot-tag-face ((t (:foreground "light blue"))))
     (emacs-wiki-header-1 ((t (:inherit variable-pitch :foreground "LightBlue" :slant normal :weight bold :height 1.4))))
     (emacs-wiki-header-2 ((t (:inherit variable-pitch :foreground "LightSkyBlue1" :weight bold :height 1.3))))
     (emacs-wiki-header-3 ((t (:inherit variable-pitch :foreground "LightSkyBlue2" :height 1.3))))
     (emacs-wiki-header-4 ((t (:inherit variable-pitch :foreground "LightSkyBlue3" :slant italic :height 1.1))))
     (emacs-wiki-header-5 ((t (:inherit variable-pitch :foreground "LightSkyBlue3" :height 1.0))))
     (emacs-wiki-bad-link-face ((t (:bold t :foreground "firebrick" :underline "firebrick" :weight bold ))))
     (emacs-wiki-link-face ((t (:bold t :foreground "LightSalmon" :underline "LightSalmon" :weight bold ))))
     (emacs-wiki-verbatim-face ((t (:foreground "gray"))))
     (emms-pbi-current-face ((t (:bold t :foreground "yellow" :weight bold))))
     (emms-pbi-mark-marked-face ((t (:bold t :foreground "green" :weight bold))))
     (emms-pbi-song-face ((t (nil))))
     (erc-action-face ((t (:bold t :weight bold))))
     (erc-bold-face ((t (:bold t :weight bold))))
     (erc-command-indicator-face ((t (:bold t :weight bold))))
     (erc-current-nick-face ((t (:bold t :foreground "yellow" :weight bold))))
     (erc-dangerous-host-face ((t (:foreground "red"))))
     (erc-default-face ((t (nil))))
     (erc-direct-msg-face ((t (:foreground "LightSalmon"))))
     (erc-error-face ((t (:bold t :foreground "yellow" :weight bold))))
     (erc-fool-face ((t (:foreground "dim gray"))))
     (erc-highlight-face ((t (:bold t :foreground "pale green" :weight bold))))
     (erc-input-face ((t (:foreground "Beige"))))
     (erc-inverse-face ((t (:background "wheat" :foreground "darkslategrey"))))
     (erc-keyword-face ((t (:bold t :foreground "orange" :weight bold))))
     (erc-nick-default-face ((t (:bold t :weight bold))))
     (erc-nick-msg-face ((t (:bold t :foreground "IndianRed" :weight bold))))
     (erc-notice-face ((t (:foreground "MediumAquamarine"))))
     (erc-pal-face ((t (:foreground "PaleGreen"))))
     (erc-prompt-face ((t (:foreground "MediumAquamarine"))))
     (erc-timestamp-face ((t (:bold t :foreground "green" :weight bold))))
     (erc-underline-face ((t (:underline t))))
     (escape-glyph ((t (:foreground "cyan"))))
     (eshell-ls-archive-face ((t (:bold t :foreground "wheat" :weight bold))))
     (eshell-ls-backup-face ((t (:foreground "Grey"))))
     (eshell-ls-clutter-face ((t (:bold t :foreground "wheat" :weight bold))))
     (eshell-ls-directory-face ((t (:bold t :foreground "Yellow" :weight bold))))
     (eshell-ls-executable-face ((t (:bold t :foreground "wheat" :weight bold))))
     (eshell-ls-missing-face ((t (:bold t :foreground "wheat" :weight bold))))
     (eshell-ls-picture-face ((t (:foreground "wheat"))))
     (eshell-ls-product-face ((t (:foreground "wheat"))))
     (eshell-ls-readonly-face ((t (:foreground "wheat"))))
     (eshell-ls-special-face ((t (:bold t :foreground "wheat" :weight bold))))
     (eshell-ls-symlink-face ((t (:bold t :foreground "White" :weight bold))))
     (eshell-ls-text-face ((t (:foreground "wheat"))))
     (eshell-ls-todo-face ((t (:foreground "wheat"))))
     (eshell-ls-unreadable-face ((t (:foreground "wheat3"))))
     (eshell-prompt-face ((t (:bold t :foreground "PaleGreen" :weight bold))))
     (eshell-test-failed-face ((t (:bold t :foreground "OrangeRed" :weight bold))))
     (eshell-test-ok-face ((t (:bold t :foreground "Green" :weight bold))))
     (excerpt ((t (:italic t :slant italic))))
     (ff-paths-non-existant-file-face ((t (:bold t :foreground "NavyBlue" :weight bold))))
     (fg:black ((t (:foreground "black"))))
     (fg:erc-color-face0 ((t (:foreground "White"))))
     (fg:erc-color-face1 ((t (:foreground "black"))))
     (fg:erc-color-face10 ((t (:foreground "lightblue1"))))
     (fg:erc-color-face11 ((t (:foreground "cyan"))))
     (fg:erc-color-face12 ((t (:foreground "blue"))))
     (fg:erc-color-face13 ((t (:foreground "deeppink"))))
     (fg:erc-color-face14 ((t (:foreground "gray50"))))
     (fg:erc-color-face15 ((t (:foreground "gray90"))))
     (fg:erc-color-face2 ((t (:foreground "blue4"))))
     (fg:erc-color-face3 ((t (:foreground "green4"))))
     (fg:erc-color-face4 ((t (:foreground "red"))))
     (fg:erc-color-face5 ((t (:foreground "brown"))))
     (fg:erc-color-face6 ((t (:foreground "purple"))))
     (fg:erc-color-face7 ((t (:foreground "orange"))))
     (fg:erc-color-face8 ((t (:foreground "yellow"))))
     (fg:erc-color-face9 ((t (:foreground "green"))))
     (file-name-shadow ((t (:foreground "grey70"))))
     (fixed ((t (:bold t :weight bold))))
     (fixed-pitch ((t (:family "courier"))))
     (fl-comment-face ((t (:foreground "medium purple"))))
     (fl-function-name-face ((t (:foreground "green"))))
     (fl-keyword-face ((t (:foreground "LightGreen"))))
     (fl-string-face ((t (:foreground "light coral"))))
     (fl-type-face ((t (:foreground "cyan"))))
     (flymake-errline-face ((t (:underline "light salmon"))))
     (flymake-warnline-face ((t (:underline "LightBlue2"))))
     (flyspell-duplicate-face ((t (:bold t :foreground "Gold3" :underline t :weight bold))))
     (flyspell-incorrect-face ((t (:bold t :foreground "OrangeRed" :underline t :weight bold))))
     (font-latex-italic-face ((t (nil))))
     (font-latex-math-face ((t (nil))))
     (font-latex-sedate-face ((t (:foreground "Gray85"))))
     (font-latex-string-face ((t (:foreground "orange"))))
     (font-latex-warning-face ((t (:foreground "gold"))))
     (font-lock-builtin-face ((t (:foreground "PaleTurquoise"))))
     (font-lock-comment-delimiter-face ((t (:foreground "Gray80"))))
     (font-lock-comment-face ((t (:foreground "Gray80"))))
     (font-lock-constant-face ((t (:foreground "LightBlue"))))
     (font-lock-doc-face ((t (:foreground "AntiqueWhite3"))))
     (font-lock-doc-string-face ((t (:bold t :foreground "DarkSeaGreen3" :weight bold))))
     (font-lock-exit-face ((t (:foreground "green"))))
     (font-lock-function-name-face ((t (:bold t :foreground "LightSalmon" :weight bold))))
     (font-lock-keyword-face ((t (:bold t :foreground "LightBlue" :weight bold))))
     (font-lock-negation-char-face ((t (nil))))
     (font-lock-preprocessor-face ((t (:foreground "blue3"))))
     (font-lock-reference-face ((t (:foreground "PaleGreen"))))
     (font-lock-regexp-grouping-backslash ((t (:bold t :weight bold :foreground "MediumAquamarine"))))
     (font-lock-regexp-grouping-construct ((t (:bold t :weight bold :foreground "MediumAquamarine"))))
     (font-lock-string-face ((t (:foreground "DarkSeaGreen2" ))))
     (font-lock-type-face ((t (:bold t :foreground "LightSkyBlue" :weight bold))))
     (font-lock-variable-name-face ((t (:bold t :foreground "LightBlue" :weight bold))))
     (font-lock-warning-face ((t (:bold t :foreground "coral" :weight bold))))
     (fringe ((t (:background "#587687"))))
     (gnus-cite-attribution-face ((t (:italic t :bold t :slant italic :weight bold))))
     (gnus-cite-face-1 ((t (:foreground "LightBlue"))))
     (gnus-cite-face-10 ((t (:foreground "LightBlue"))))
     (gnus-cite-face-11 ((t (:foreground "LightBlue"))))
     (gnus-cite-face-2 ((t (:foreground "LightBlue"))))
     (gnus-cite-face-3 ((t (:foreground "LightBlue"))))
     (gnus-cite-face-4 ((t (:foreground "LightBlue"))))
     (gnus-cite-face-5 ((t (:foreground "LightBlue"))))
     (gnus-cite-face-6 ((t (:foreground "LightBlue"))))
     (gnus-cite-face-7 ((t (:foreground "LightBlue"))))
     (gnus-cite-face-8 ((t (:foreground "LightBlue"))))
     (gnus-cite-face-9 ((t (:foreground "LightBlue"))))
     (gnus-cite-face-list ((t (:bold t :foreground "red" :weight bold))))
     (gnus-emphasis-bold ((t (:bold t :weight bold))))
     (gnus-emphasis-bold-italic ((t (:italic t :bold t :slant italic :weight bold))))
     (gnus-emphasis-highlight-words ((t (:background "black" :foreground "yellow"))))
     (gnus-emphasis-italic ((t (:italic t :slant italic))))
     (gnus-emphasis-strikethru ((t (:strike-through t))))
     (gnus-emphasis-underline ((t (:underline t))))
     (gnus-emphasis-underline-bold ((t (:bold t :underline t :weight bold))))
     (gnus-emphasis-underline-bold-italic ((t (:italic t :bold t :underline t :slant italic :weight bold))))
     (gnus-emphasis-underline-italic ((t (:italic t :underline t :slant italic))))
     (gnus-filterhist-face-1 ((t (nil))))
     (gnus-group-mail-1 ((t (:bold t :foreground "light cyan" :weight bold))))
     (gnus-group-mail-1-empty ((t (:foreground "gray80"))))
     (gnus-group-mail-2 ((t (:bold t :foreground "turquoise" :weight bold))))
     (gnus-group-mail-2-empty ((t (:foreground "gray80"))))
     (gnus-group-mail-3 ((t (:bold t :foreground "LightBlue" :weight bold))))
     (gnus-group-mail-3-empty ((t (:foreground "gray80"))))
     (gnus-group-mail-low ((t (:bold t :foreground "LightBlue" :weight bold))))
     (gnus-group-mail-low-empty ((t (:foreground "gray80"))))
     (gnus-group-news-1 ((t (:bold t :foreground "green yellow" :weight bold))))
     (gnus-group-news-1-empty ((t (:foreground "gray80"))))
     (gnus-group-news-2 ((t (:bold t :foreground "Aquamarine" :weight bold))))
     (gnus-group-news-2-empty ((t (:foreground "gray80"))))
     (gnus-group-news-3 ((t (:bold t :foreground "LightBlue" :weight bold))))
     (gnus-group-news-3-empty ((t (:foreground "gray80"))))
     (gnus-group-news-4 ((t (:bold t :foreground "Wheat" :weight bold))))
     (gnus-group-news-4-empty ((t (:foreground "gray80"))))
     (gnus-group-news-5 ((t (:bold t :foreground "MediumAquamarine" :weight bold))))
     (gnus-group-news-5-empty ((t (:foreground "gray80"))))
     (gnus-group-news-6 ((t (:bold t :foreground "MediumAquamarine" :weight bold))))
     (gnus-group-news-6-empty ((t (:foreground "gray80"))))
     (gnus-group-news-low ((t (:bold t :foreground "yellow green" :weight bold))))
     (gnus-group-news-low-empty ((t (:foreground "gray80"))))
     (gnus-header-content ((t (:italic t :foreground "LightSkyBlue3" :slant italic))))
     (gnus-header-from ((t (:bold t :foreground "light cyan" :weight bold))))
     (gnus-header-name ((t (:bold t :foreground "LightBlue" :weight bold))))
     (gnus-header-newsgroups ((t (:italic t :bold t :foreground "LightSkyBlue3" :slant italic :weight bold))))
     (gnus-header-subject ((t (:bold t :foreground "light cyan" :weight bold))))
     (gnus-picons-face ((t (:background "white" :foreground "black"))))
     (gnus-picons-xbm-face ((t (:background "white" :foreground "black"))))
     (gnus-signature ((t (:italic t :foreground "LightBlue" :slant italic))))
     (gnus-splash ((t (:foreground "Brown"))))
     (gnus-summary-cancelled ((t (:background "black" :foreground "gray80"))))
     (gnus-summary-high-ancient ((t (:bold t :foreground "LightBlue" :weight bold))))
     (gnus-summary-high-read ((t (:bold t :foreground "gray80" :weight bold))))
     (gnus-summary-high-ticked ((t (:bold t :foreground "burlywood" :weight bold))))
     (gnus-summary-high-undownloaded ((t (:bold t :foreground "cyan4" :weight bold))))
     (gnus-summary-high-unread ((t (:italic t :bold t :foreground "wheat" :slant italic :weight bold))))
     (gnus-summary-low-ancient ((t (:italic t :foreground "LightBlue" :slant italic))))
     (gnus-summary-low-read ((t (:italic t :foreground "light sea green" :slant italic))))
     (gnus-summary-low-ticked ((t (:italic t :bold t :foreground "LightBlue" :slant italic :weight bold))))
     (gnus-summary-low-undownloaded ((t (:italic t :foreground "cyan4" :slant italic :weight normal))))
     (gnus-summary-low-unread ((t (:italic t :foreground "light sea green" :slant italic))))
     (gnus-summary-normal-ancient ((t (:foreground "gray80"))))
     (gnus-summary-normal-read ((t (:foreground "gray80"))))
     (gnus-summary-normal-ticked ((t (:bold t :foreground "sandy brown" :weight bold))))
     (gnus-summary-normal-undownloaded ((t (:foreground "cyan4" :weight normal))))
     (gnus-summary-normal-unread ((t (:bold t :foreground "wheat" :weight bold))))
     (gnus-summary-selected ((t (:underline t))))
     (gnus-x-face ((t (:background "white" :foreground "black"))))
     (green ((t (:foreground "green"))))
     (gui-button-face ((t (:background "DarkSalmon" :foreground "white"))))
     (gui-element ((t (:background "Gray"))))
     (header-line ((t (:background "grey20" :foreground "grey90"))))
     (help-argument-name ((t (nil))))
     (hexl-address-region ((t (:foreground "grey90" :background "grey20"))))
     (hexl-ascii-region ((t (:foreground "grey90" :background "grey20"))))
     (highlight ((t (:background "LightSkyBlue" :foreground "DarkSlateGrey"))))
     (highlight-changes-delete-face ((t (:foreground "red" :underline t))))
     (highlight-changes-face ((t (:foreground "red"))))
     (highline-face ((t (:background "SeaGreen"))))
     (hl-sexp-face ((t (:background "#577586"))))
     (holiday ((t (:background "DimGray"))))
     (horizontal-divider ((t (:background "gray16" :foreground "#00ff00"))))
     (html-helper-bold-face ((t (:foreground "DarkRed"))))
     (html-helper-bold-italic-face ((t (nil))))
     (html-helper-builtin-face ((t (:foreground "blue3" :underline t))))
     (html-helper-italic-face ((t (:foreground "DarkBlue"))))
     (html-helper-underline-face ((t (:foreground "Black" :underline t))))
     (html-tag-face ((t (:foreground "Blue"))))
     (hyper-apropos-documentation ((t (:foreground "LightSalmon"))))
     (hyper-apropos-heading ((t (:bold t :weight bold))))
     (hyper-apropos-hyperlink ((t (:bold t :foreground "DodgerBlue1" :weight bold))))
     (hyper-apropos-major-heading ((t (:bold t :weight bold))))
     (hyper-apropos-section-heading ((t (:bold t :weight bold))))
     (hyper-apropos-warning ((t (:bold t :foreground "red" :weight bold))))
     (ibuffer-marked-face ((t (:foreground "red"))))
     (ido-first-match ((t (:foreground "PaleTurquoise"))))
     (ido-incomplete-regexp ((t (:bold t :weight bold :foreground "LightSalmon"))))
     (ido-indicator ((t (:background "red1" :foreground "yellow1" :width condensed))))
     (ido-only-match ((t (:bold t :foreground "PaleTurquoise1" :weight bold))))
     (ido-subdir ((t (:bold t :foreground "LightSalmon" :weight bold))))
     (info-header-node ((t (:bold t :weight bold :underline t :foreground "light blue"))))
     (info-header-xref ((t (:bold t :foreground "DodgerBlue1" :weight bold))))
     (info-menu-6 ((t (nil))))
     (info-menu-header ((t (:bold t :weight bold))))
     (info-menu-star ((t (:underline t))))
     (info-node ((t (:bold t :foreground "light blue" :underline t :weight bold))))
     (info-title-1 ((t (:foreground "light blue" :bold t :weight bold :height 1.728))))
     (info-title-2 ((t (:foreground "light blue" :bold t :weight bold :height 1.44))))
     (info-title-3 ((t (:foreground "light blue" :bold t :weight bold :height 1.2))))
     (info-title-4 ((t (:foreground "light blue" :bold t :weight bold))))
     (info-xref ((t (:foreground "light blue" :underline t))))
     (info-xref-visited ((t (:foreground "violet" :underline t))))
     (isearch ((t (:background "Aquamarine" :foreground "SteelBlue"))))
     (isearch-secondary ((t (:foreground "red3"))))
     (italic ((t (:italic t :slant italic))))
     (jde-bug-breakpoint-cursor ((t (:background "brown" :foreground "cyan"))))
     (jde-bug-breakpoint-marker ((t (:background "yellow" :foreground "red"))))
     (jde-db-active-breakpoint-face ((t (:background "red" :foreground "black"))))
     (jde-db-requested-breakpoint-face ((t (:background "yellow" :foreground "black"))))
     (jde-db-spec-breakpoint-face ((t (:background "green" :foreground "black"))))
     (jde-java-font-lock-api-face ((t (:foreground "LightBlue"))))
     (jde-java-font-lock-bold-face ((t (:bold t :weight bold))))
     (jde-java-font-lock-code-face ((t (nil))))
     (jde-java-font-lock-constant-face ((t (:foreground "LightBlue"))))
     (jde-java-font-lock-doc-tag-face ((t (:foreground "LightBlue"))))
     (jde-java-font-lock-italic-face ((t (:italic t :slant italic))))
     (jde-java-font-lock-link-face ((t (:foreground "LightBlue" :underline t))))
     (jde-java-font-lock-modifier-face ((t (:foreground "LightBlue"))))
     (jde-java-font-lock-number-face ((t (:foreground "LightBlue"))))
     (jde-java-font-lock-operator-face ((t (:foreground "medium blue"))))
     (jde-java-font-lock-package-face ((t (:foreground "LightBlue"))))
     (jde-java-font-lock-pre-face ((t (nil))))
     (jde-java-font-lock-underline-face ((t (:underline t))))
     (lazy-highlight ((t (:background "paleturquoise4"))))
     (lazy-highlight-face ((t (:bold t :foreground "dark magenta" :weight bold))))
     (left-margin ((t (nil))))
     (linemenu-face ((t (:background "gray30"))))
     (link ((t (:foreground "cyan1" :underline t))))
     (link-visited ((t (:underline t :foreground "violet"))))
     (list-mode-item-selected ((t (nil))))
     (log-view-message-face ((t (:foreground "light salmon"))))
     (magenta ((t (:foreground "magenta"))))
     (makefile-space-face ((t (:background "hotpink"))))
     (man-bold ((t (:bold t :weight bold))))
     (man-heading ((t (:bold t :weight bold))))
     (man-italic ((t (:foreground "yellow"))))
     (man-xref ((t (:underline t))))
     (match ((t (:background "RoyalBlue3"))))
     (menu ((t (:background "wheat" :foreground "gray30"))))
     (message-cited-text ((t (:foreground "White"))))
     (message-header-cc ((t (:bold t :foreground "light cyan" :weight bold))))
     (message-header-contents ((t (:foreground "white"))))
     (message-header-name ((t (:foreground "LightBlue"))))
     (message-header-newsgroups ((t (:italic t :bold t :foreground "LightSkyBlue3" :slant italic :weight bold))))
     (message-header-other ((t (:foreground "LightSkyBlue3"))))
     (message-header-subject ((t (:bold t :foreground "light cyan" :weight bold))))
     (message-header-to ((t (:bold t :foreground "light cyan" :weight bold))))
     (message-header-xheader ((t (:foreground "LightBlue"))))
     (message-headers ((t (:bold t :foreground "orange" :weight bold))))
     (message-highlighted-header-contents ((t (:bold t :weight bold))))
     (message-mml ((t (:bold t :foreground "LightBlue" :weight bold))))
     (message-separator ((t (:foreground "LightBlue"))))
     (message-url ((t (:bold t :foreground "pink" :weight bold))))
     (minibuffer-prompt ((t (:foreground "NavajoWhite"))))
     (mm-uu-extract ((t (:background "dark green" :foreground "light yellow"))))
     (mmm-default-submode-face ((t (:background "#c0c0c5"))))
     (mmm-face ((t (:background "black" :foreground "green"))))
     (moccur-current-line-face ((t (:underline t))))
     (moccur-face ((t (:bold t :background "light cyan" :weight bold))))
     (mode-line ((t (:bold t :background "#c1ccd9" :foreground "gray30" :overline "PaleTurquoise4" :underline "PaleTurquoise3" :weight bold))))
     (mode-line-buffer-id ((t (:background "#c1ccd9" :foreground "#4f657d"))))
     (mode-line-highlight ((t (:box (:line-width 2 :color "grey40" :style released-button)))))
     (mode-line-inactive ((t (:underline "PaleTurquoise3" :overline "PaleTurquoise4" :background "#c1ccd9" :stipple nil :foreground "#4f657d" :overline nil :underline nil :weight light))))
     (modeline-mousable ((t (:background "#c1ccd9" :foreground "#4f657d"))))
     (modeline-mousable-minor-mode ((t (:background "#c1ccd9" :foreground "#4f657d"))))
     (mouse ((t (:background "Grey"))))
     (muse-bad-link-face ((t (:foreground "violet"))))
     (muse-emphasis-1 ((t (:inherit variable-pitch :slant italic))))
     (muse-emphasis-3 ((t (:inherit variable-pitch :slant italic :weight bold))))
     (muse-header-1 ((t (:inherit variable-pitch :foreground "LightBlue" :weight bold :height 1.4))))
     (muse-header-2 ((t (:inherit variable-pitch :foreground "LightBlue2" :weight bold :height 1.3))))
     (muse-header-3 ((t (:inherit variable-pitch :foreground "LightSkyBlue2" :height 1.2))))
     (muse-header-4 ((t (:inherit variable-pitch :foreground "LightSkyBlue3" :slant italic :height 1.1))))
     (muse-header-5 ((t (:inherit variable-pitch :foreground "LightSkyBlue3" :height 1.0))))
     (muse-link-face ((t (:foreground "darkslateblue" :underline "darkslateblue"))))
     (my-summary-highlight-face ((t (:foreground "White"))))
     (my-url-face ((t (:foreground "LightBlue"))))
     (next-error ((t (:foreground "gray80" :background "PaleTurquoise4"))))
     (nil ((t (nil))))
     (nobreak-space ((t (:foreground "cyan" :underline t))))
     (nxml-attribute-colon-face ((t (:inherit font-lock-builtin-face))))
     (nxml-attribute-local-name-face ((t (:inherit font-lock-variable-name-face :weight normal))))
     (nxml-attribute-prefix-face ((t (:inherit font-lock-type-face))))
     (nxml-attribute-value-delimiter-face ((t (:inherit font-lock-string-face))))
     (nxml-attribute-value-face ((t (:inherit font-lock-string-face))))
     (nxml-cdata-section-CDATA-face ((t (:inherit font-lock-keyword-face))))
     (nxml-cdata-section-content-face ((t (nil))))
     (nxml-cdata-section-delimiter-face ((t (:inherit paren-face))))
     (nxml-char-ref-delimiter-face ((t (:inherit paren-face))))
     (nxml-char-ref-number-face ((t (:inherit font-lock-keyword-face))))
     (nxml-comment-content-face ((t (:inherit font-lock-comment-face))))
     (nxml-comment-delimiter-face ((t (:inherit font-lock-comment-face))))
     (nxml-delimited-data-face ((t (:inherit font-lock-string-face))))
     (nxml-delimiter-face ((t (:inherit paren-face))))
     (nxml-element-colon-face ((t (:inherit font-lock-builtin-face))))
     (nxml-element-local-name-face ((t (:inherit font-lock-variable-name-face :weight normal))))
     (nxml-element-prefix-face ((t (:inherit font-lock-type-face))))
     (nxml-entity-ref-delimiter-face ((t (:inherit paren-face))))
     (nxml-entity-ref-name-face ((t (:inherit font-lock-keyword-face))))
     (nxml-glyph-face ((t (:inherit font-lock-builtin-face))))
     (nxml-hash-face ((t (:inherit font-lock-keyword-face))))
     (nxml-heading-face ((t (:bold t :weight bold))))
     (nxml-markup-declaration-delimiter-face ((t (:inherit paren-face))))
     (nxml-name-face ((t (:inherit font-lock-type-face :weight normal))))
     (nxml-namespace-attribute-colon-face ((t (:inherit font-lock-builtin-face))))
     (nxml-namespace-attribute-prefix-face ((t (:inherit font-lock-type-face))))
     (nxml-namespace-attribute-value-delimiter-face ((t (:inherit font-lock-string-face))))
     (nxml-namespace-attribute-value-face ((t (:inherit font-lock-string-face))))
     (nxml-namespace-attribute-xmlns-face ((t (:inherit font-lock-type-face))))
     (nxml-outline-active-indicator-face ((t (:foreground "LightSalmon" :box 1 :height 103))))
     (nxml-outline-ellipsis-face ((t (:bold t :foreground "LightSalmon" :weight bold :height 103))))
     (nxml-outline-indicator-face ((t (:foreground "LightSalmon" :height 103))))
     (nxml-processing-instruction-content-face ((t (:inherit font-lock-string-face))))
     (nxml-processing-instruction-delimiter-face ((t (:inherit paren-face))))
     (nxml-processing-instruction-target-face ((t (:inherit font-lock-keyword-face))))
     (nxml-prolog-keyword-face ((t (:inherit font-lock-type-face))))
     (nxml-prolog-literal-content-face ((t (:inherit font-lock-string-face))))
     (nxml-prolog-literal-delimiter-face ((t (:inherit font-lock-string-face))))
     (nxml-ref-face ((t (:foreground "LightSalmon"))))
     (nxml-tag-delimiter-face ((t (:inherit paren-face))))
     (nxml-tag-slash-face ((t (:inherit paren-face))))
     (nxml-text-face ((t (:inherit default))))
     (outline-1 ((t (:italic t :bold t :weight bold :slant italic :foreground "LightSalmon"))))
     (outline-2 ((t (:italic t :bold t :weight bold :slant italic :foreground "LightBlue"))))
     (outline-3 ((t (:bold t :weight bold :foreground "LightBlue"))))
     (outline-4 ((t (:foreground "PaleTurquoise"))))
     (outline-5 ((t (:italic t :slant italic :foreground "Gray80"))))
     (outline-6 ((t (:foreground "LightBlue"))))
     (outline-7 ((t (:bold t :weight bold :foreground "OliveDrab3"))))
     (outline-8 ((t (:italic t :slant italic :foreground "DarkSeaGreen2"))))
     (paren-blink-off ((t (:foreground "gray"))))
     (paren-face ((t (:foreground "AntiqueWhite3"))))
     (paren-face-match ((t (:background "turquoise"))))
     (paren-face-mismatch ((t (:background "purple" :foreground "white"))))
     (paren-face-no-match ((t (:background "yellow" :foreground "black"))))
     (paren-match ((t (:background "darkseagreen2"))))
     (paren-mismatch ((t (:background "DeepPink" :foreground "black"))))
     (paren-mismatch-face ((t (:bold t :weight bold))))
     (paren-no-match-face ((t (:bold t :weight bold))))
     (planner-cancelled-task-face ((t (:foreground "gray" :strike-through t))))
     (planner-completed-task-face ((t (:foreground "gray" :strike-through t))))
     (planner-delegated-task-face ((t (:underline t))))
     (planner-high-priority-task-face ((t (:foreground "red"))))
     (planner-in-progress-task-face ((t (:italic t :slant oblique))))
     (planner-low-priority-task-face ((t (:foreground "blue"))))
     (planner-medium-priority-task-face ((t (:foreground "green"))))
     (planner-note-headline-face ((t (:bold t :foreground "dark slate blue" :weight bold))))
     (pointer ((t (nil))))
     (primary-selection ((t (:background "gray65"))))
     (query-replace ((t (:foreground "SteelBlue" :background "Aquamarine"))))
     (red ((t (:foreground "red"))))
     (region ((t (:background "orange3"))))
     (right-margin ((t (nil))))
     (scroll-bar ((t (nil))))
     (search-buffers-face ((t (:bold t :background "ForestGreen" :weight bold))))
     (search-buffers-header-face ((t (:bold t :background "ForestGreen" :weight bold))))
     (secondary-selection ((t (:background "sea green" :foreground "yellow"))))
     (semantic-decoration-on-private-members-face ((t (:background "#100000"))))
     (semantic-decoration-on-protected-members-face ((t (:background "#000010"))))
     (semantic-dirty-token-face ((t (:background "gray10"))))
     (semantic-highlight-edits-face ((t (:background "gray20"))))
     (semantic-intangible-face ((t (:foreground "gray25"))))
     (semantic-read-only-face ((t (:background "gray25"))))
     (semantic-tag-boundary-face ((t (:overline "cyan"))))
     (semantic-unmatched-syntax-face ((t (:underline "red"))))
     (senator-intangible-face ((t (:foreground "gray75"))))
     (senator-momentary-highlight-face ((t (:background "gray80"))))
     (senator-read-only-face ((t (:background "#664444"))))
     (sgml-comment-face ((t (:foreground "dark turquoise"))))
     (sgml-doctype-face ((t (:foreground "red"))))
     (sgml-end-tag-face ((t (:foreground "blue"))))
     (sgml-entity-face ((t (:foreground "magenta"))))
     (sgml-ignored-face ((t (:background "gray60" :foreground "gray40"))))
     (sgml-ms-end-face ((t (:foreground "green"))))
     (sgml-ms-start-face ((t (:foreground "yellow"))))
     (sgml-namespace ((t (:foreground "PaleTurquoise"))))
     (sgml-pi-face ((t (:foreground "lime green"))))
     (sgml-sgml-face ((t (:foreground "brown"))))
     (sgml-short-ref-face ((t (:foreground "deep sky blue"))))
     (sgml-start-tag-face ((t (:foreground "dark green"))))
     (shadow ((t (:foreground "grey70"))))
     (shell-option-face ((t (:foreground "blue"))))
     (shell-output-2-face ((t (:foreground "darkseagreen"))))
     (shell-output-3-face ((t (:foreground "slategray"))))
     (shell-output-face ((t (:foreground "palegreen"))))
     (shell-prompt-face ((t (:foreground "red"))))
     (show-paren-match ((t (:background "Aquamarine" :foreground "steel blue"))))
     (show-paren-mismatch ((t (:bold t :background "IndianRed" :foreground "White" :weight bold))))
     (show-tabs-space ((t (:background "yellow1"))))
     (show-tabs-tab ((t (:background "red1"))))
     (sldb-catch-tag-face ((t (:foreground "PaleGreen"))))
     (sldb-condition-face ((t (:foreground "LightSalmon"))))
     (sldb-detailed-frame-line-face ((t (:foreground "LightBlue"))))
     (sldb-frame-label-face ((t (:bold t :weight bold))))
     (sldb-frame-line-face ((t (nil))))
     (sldb-local-name-face ((t (:foreground "LightBlue"))))
     (sldb-local-value-face ((t (:foreground "PaleGreen"))))
     (sldb-reference-face ((t (:underline t))))
     (sldb-restart-face ((t (:foreground "LightBlue"))))
     (sldb-restart-number-face ((t (:bold t :weight bold))))
     (sldb-restart-type-face ((t (:bold t :weight bold :foreground "LightSkyBlue"))))
     (sldb-section-face ((t (nil))))
     (sldb-topline-face ((t (:foreground "PaleGreen"))))
     (slime-error-face ((t (:underline "red"))))
     (slime-highlight-edits-face ((t (:background "dimgray"))))
     (slime-highlight-face ((t (:foreground "DarkGreen" :background "PaleGreen" :underline nil))))
     (slime-inspector-action-face ((t (:bold t :weight bold :foreground "DarkSeaGreen2"))))
     (slime-inspector-label-face ((t (:foreground "LightBlue"))))
     (slime-inspector-topline-face ((t (:bold t :foreground "LightSalmon" :weight bold))))
     (slime-inspector-type-face ((t (:bold t :weight bold :foreground "OliveDrab3"))))
     (slime-inspector-value-face ((t (:foreground "PaleTurquoise"))))
     (slime-note-face ((t (:underline "LightGoldenrod2"))))
     (slime-reader-conditional-face ((t (:italic t :slant italic :foreground "Gray80"))))
     (slime-repl-input-face ((t (:bold t :weight bold))))
     (slime-repl-inputed-output-face ((t (:foreground "LightGoldenrod2"))))
     (slime-repl-output-face ((t (:italic t :slant italic :foreground "DarkSeaGreen2"))))
     (slime-repl-output-mouseover-face ((t (:foreground "LightGoldenrod1" :box (:line-width 1 :color "LightGoldenrod1" :style released-button)))))
     (slime-repl-prompt-face ((t (:bold t :weight bold :foreground "LightBlue"))))
     (slime-repl-result-face ((t (nil))))
     (slime-style-warning-face ((t (:underline "gold"))))
     (slime-warning-face ((t (:underline "coral"))))
     (spam ((t (:foreground "ivory2"))))
     (speedbar-button-face ((t (:bold t :foreground "LightBlue" :weight bold))))
     (speedbar-directory-face ((t (:bold t :foreground "yellow" :weight bold))))
     (speedbar-file-face ((t (:bold t :foreground "wheat" :weight bold))))
     (speedbar-highlight-face ((t (:background "sea green"))))
     (speedbar-selected-face ((t (:underline t))))
     (speedbar-separator-face ((t (:background "blue" :foreground "white" :overline "gray"))))
     (speedbar-tag-face ((t (:foreground "LightBlue"))))
     (swbuff-current-buffer-face ((t (:bold t :foreground "red" :weight bold))))
     (template-message-face ((t (:bold t :weight bold))))
     (term-black ((t (:foreground "black"))))
     (term-blackbg ((t (:background "black"))))
     (term-blue ((t (:foreground "blue"))))
     (term-blue-bold-face ((t (:bold t :background "snow2" :foreground "blue" :weight bold))))
     (term-blue-face ((t (:foreground "blue"))))
     (term-blue-inv-face ((t (:background "blue"))))
     (term-blue-ul-face ((t (:background "snow2" :foreground "blue" :underline t))))
     (term-bluebg ((t (:background "blue"))))
     (term-bold ((t (:bold t :weight bold))))
     (term-cyan ((t (:foreground "cyan"))))
     (term-cyan-bold-face ((t (:bold t :background "snow2" :foreground "cyan" :weight bold))))
     (term-cyan-face ((t (:foreground "cyan"))))
     (term-cyan-inv-face ((t (:background "cyan"))))
     (term-cyan-ul-face ((t (:background "snow2" :foreground "cyan" :underline t))))
     (term-cyanbg ((t (:background "cyan"))))
     (term-default-bg ((t (nil))))
     (term-default-bg-inv ((t (nil))))
     (term-default-bold-face ((t (:bold t :background "snow2" :foreground "darkslategray" :weight bold))))
     (term-default-face ((t (:background "snow2" :foreground "darkslategray"))))
     (term-default-fg ((t (nil))))
     (term-default-fg-inv ((t (nil))))
     (term-default-inv-face ((t (:background "darkslategray" :foreground "snow2"))))
     (term-default-ul-face ((t (:background "snow2" :foreground "darkslategray" :underline t))))
     (term-green ((t (:foreground "green"))))
     (term-green-bold-face ((t (:bold t :background "snow2" :foreground "green" :weight bold))))
     (term-green-face ((t (:foreground "green"))))
     (term-green-inv-face ((t (:background "green"))))
     (term-green-ul-face ((t (:background "snow2" :foreground "green" :underline t))))
     (term-greenbg ((t (:background "green"))))
     (term-invisible ((t (nil))))
     (term-invisible-inv ((t (nil))))
     (term-magenta ((t (:foreground "magenta"))))
     (term-magenta-bold-face ((t (:bold t :background "snow2" :foreground "magenta" :weight bold))))
     (term-magenta-face ((t (:foreground "magenta"))))
     (term-magenta-inv-face ((t (:background "magenta"))))
     (term-magenta-ul-face ((t (:background "snow2" :foreground "magenta" :underline t))))
     (term-magentabg ((t (:background "magenta"))))
     (term-red ((t (:foreground "red"))))
     (term-red-bold-face ((t (:bold t :background "snow2" :foreground "red" :weight bold))))
     (term-red-face ((t (:foreground "red"))))
     (term-red-inv-face ((t (:background "red"))))
     (term-red-ul-face ((t (:background "snow2" :foreground "red" :underline t))))
     (term-redbg ((t (:background "red"))))
     (term-underline ((t (:underline t))))
     (term-white ((t (:foreground "white"))))
     (term-white-bold-face ((t (:bold t :background "snow2" :foreground "white" :weight bold))))
     (term-white-face ((t (:foreground "white"))))
     (term-white-inv-face ((t (:background "snow2"))))
     (term-white-ul-face ((t (:background "snow2" :foreground "white" :underline t))))
     (term-whitebg ((t (:background "white"))))
     (term-yellow ((t (:foreground "yellow"))))
     (term-yellow-bold-face ((t (:bold t :background "snow2" :foreground "yellow" :weight bold))))
     (term-yellow-face ((t (:foreground "yellow"))))
     (term-yellow-inv-face ((t (:background "yellow"))))
     (term-yellow-ul-face ((t (:background "snow2" :foreground "yellow" :underline t))))
     (term-yellowbg ((t (:background "yellow"))))
     (text-cursor ((t (:background "Red3" :foreground "white"))))
     (tool-bar ((t (:background "grey75" :foreground "black"))))
     (tooltip ((t (:background "lightyellow" :foreground "black"))))
     (trailing-whitespace ((t (:background "red"))))
     (underline ((t (:underline t))))
     (variable-pitch ((t (nil))))
     (vc-annotate-face-0046FF ((t (:background "black" :foreground "wheat"))))
     (vcursor ((t (:background "cyan" :foreground "blue" :underline t))))
     (vertical-border ((t (nil))))
     (vertical-divider ((t (:background "Gray"))))
     (vhdl-font-lock-attribute-face ((t (:foreground "Orchid"))))
     (vhdl-font-lock-directive-face ((t (:foreground "CadetBlue"))))
     (vhdl-font-lock-enumvalue-face ((t (:foreground "Gold4"))))
     (vhdl-font-lock-function-face ((t (:foreground "Orchid4"))))
     (vhdl-font-lock-prompt-face ((t (:bold t :foreground "Red" :weight bold))))
     (vhdl-font-lock-reserved-words-face ((t (:bold t :foreground "Orange" :weight bold))))
     (vhdl-font-lock-translate-off-face ((t (:background "LightGray"))))
     (vhdl-speedbar-architecture-face ((t (:foreground "Blue"))))
     (vhdl-speedbar-architecture-selected-face ((t (:foreground "Blue" :underline t))))
     (vhdl-speedbar-configuration-face ((t (:foreground "DarkGoldenrod"))))
     (vhdl-speedbar-configuration-selected-face ((t (:foreground "DarkGoldenrod" :underline t))))
     (vhdl-speedbar-entity-face ((t (:foreground "ForestGreen"))))
     (vhdl-speedbar-entity-selected-face ((t (:foreground "ForestGreen" :underline t))))
     (vhdl-speedbar-instantiation-face ((t (:foreground "Brown"))))
     (vhdl-speedbar-instantiation-selected-face ((t (:foreground "Brown" :underline t))))
     (vhdl-speedbar-package-face ((t (:foreground "Gray50"))))
     (vhdl-speedbar-package-selected-face ((t (:foreground "Gray50" :underline t))))
     (viper-minibuffer-emacs-face ((t (:background "darkseagreen2" :foreground "Black"))))
     (viper-minibuffer-insert-face ((t (:background "pink" :foreground "Black"))))
     (viper-minibuffer-vi-face ((t (:background "gray" :foreground "DarkGreen"))))
     (viper-replace-overlay-face ((t (:background "darkseagreen2" :foreground "Black"))))
     (viper-search-face ((t (:background "khaki" :foreground "Black"))))
     (vm-header-content-face ((t (:italic t :foreground "wheat" :slant italic))))
     (vm-header-from-face ((t (:italic t :foreground "wheat" :slant italic))))
     (vm-header-name-face ((t (:foreground "cyan"))))
     (vm-header-subject-face ((t (:foreground "cyan"))))
     (vm-header-to-face ((t (:italic t :foreground "cyan" :slant italic))))
     (vm-message-cited-face ((t (:foreground "Gray80"))))
     (vm-summary-face-1 ((t (:foreground "MediumAquamarine"))))
     (vm-summary-face-2 ((t (:foreground "MediumAquamarine"))))
     (vm-summary-face-3 ((t (:foreground "MediumAquamarine"))))
     (vm-summary-face-4 ((t (:foreground "MediumAquamarine"))))
     (vm-summary-highlight-face ((t (:foreground "White"))))
     (vm-xface ((t (:background "white" :foreground "black"))))
     (vmpc-pre-sig-face ((t (:foreground "Aquamarine"))))
     (vmpc-sig-face ((t (:foreground "LightBlue"))))
     (vvb-face ((t (:background "pink" :foreground "black"))))
     (w3m-anchor-face ((t (:bold t :foreground "LightSkyBlue" :weight bold))))
     (w3m-arrived-anchor-face ((t (:bold t :foreground "LightBlue" :weight bold))))
     (w3m-bold-face ((t (:bold t :weight bold))))
     (w3m-current-anchor-face ((t (:bold t :underline t :weight bold))))
     (w3m-form-button-face ((t (:bold t :background "lightgrey" :foreground "black" :box (:line-width 2 :style released-button) :weight bold :family "Verdana"))))
     (w3m-form-button-mouse-face ((t (:background "DarkSeaGreen1" :foreground "black" :box (:line-width 2 :style released-button)))))
     (w3m-form-button-pressed-face ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style pressed-button)))))
     (w3m-header-line-location-content-face ((t (:background "dark olive green" :foreground "beige"))))
     (w3m-header-line-location-title-face ((t (:background "dark olive green" :foreground "LightSalmon"))))
     (w3m-history-current-url-face ((t (:background "yellow1" :foreground "navy"))))
     (w3m-image-face ((t (:foreground "PaleGreen"))))
     (w3m-strike-through-face ((t (:strike-through t))))
     (w3m-tab-background-face ((t (:background "LightSteelBlue" :foreground "black"))))
     (w3m-tab-mouse-face ((t (:background "Gray65" :foreground "white" :box (:line-width -1 :style released-button)))))
     (w3m-tab-selected-face ((t (:background "Gray85" :foreground "black" :box (:line-width -1 :style released-button)))))
     (w3m-tab-selected-retrieving-face ((t (:background "Gray85" :foreground "red" :box (:line-width -1 :style released-button)))))
     (w3m-tab-unselected-face ((t (:background "Gray50" :foreground "Gray20" :box (:line-width -1 :style released-button)))))
     (w3m-tab-unselected-retrieving-face ((t (:background "Gray50" :foreground "OrangeRed" :box (:line-width -1 :style released-button)))))
     (w3m-underline-face ((t (:underline t))))
     (which-func ((t (:foreground "Blue1"))))
     (white ((t (:foreground "white"))))
     (widget ((t (nil))))
     (widget-button ((t (:bold t :weight bold))))
     (widget-button-pressed ((t (:foreground "red"))))
     (widget-documentation ((t (:foreground "LightBlue"))))
     (widget-field ((t (:foreground "LightSkyBlue" :background "#608090"))))
     (widget-inactive ((t (:foreground "Wheat3"))))
     (widget-single-line-field ((t (:foreground "LightSkyBlue"  :background "#608090"))))
     (wikiarea-new-file-face ((t (:foreground "red"))))
     (wikiarea-updated-file-face ((t (:foreground "green"))))
     (woman-bold-face ((t (:bold t :weight bold))))
     (woman-italic-face ((t (:foreground "beige"))))
     (woman-unknown-face ((t (:foreground "LightSalmon"))))
     (x-face ((t (:background "white" :foreground "black"))))
     (xrdb-option-name-face ((t (:foreground "red"))))
     (xref-error-face ((t (:foreground "red"))))
     (xref-keyword-face ((t (:foreground "blue"))))
     (xref-list-default-face ((t (nil))))
     (xref-list-pilot-face ((t (:foreground "navy"))))
     (xref-list-symbol-face ((t (:foreground "navy"))))
     (xxml-emph-1-face ((t (:background "lightyellow"))))
     (xxml-emph-2-face ((t (:background "lightyellow"))))
     (xxml-header-1-face ((t (:background "seashell1" :foreground "MediumAquamarine"))))
     (xxml-header-2-face ((t (:background "seashell1" :foreground "SkyBlue"))))
     (xxml-header-3-face ((t (:background "seashell1"))))
     (xxml-header-4-face ((t (:background "seashell1"))))
     (xxml-interaction-face ((t (:background "lightcyan"))))
     (xxml-rug-face ((t (:background "cyan"))))
     (xxml-sparkle-face ((t (:background "yellow"))))
     (xxml-unbreakable-space-face ((t (:foreground "grey" :underline t))))
     (yellow ((t (:foreground "yellow"))))
     (zmacs-region ((t (:background "SlateGray")))))))
