/*
 * bad-mood.c
 * generated by gwizard 0.0.0 on Fri Nov 16 16:18:57 2001
 */

/*
** Copyright (C) 2001 Dirk-Jan C. Binnema <djcb@djcbsoftware.nl>
**
** This program is free software; you can redistribute it and/or modify
** it under the terms of the GNU General Public License as published by
** the Free Software Foundation; either version 2 of the License, or
** (at your option) any later version.
**
** This program is distributed in the hope that it will be useful,
** but WITHOUT ANY WARRANTY; without even the implied warranty of
** MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
** GNU General Public License for more details.
**
** You should have received a copy of the GNU General Public License
** along with this program; if not, write to the Free Software
** Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
**
*/

#include "bad-mood.h"

/*
 * NOTE: these may not (all) be needed. Please remove
 * unneeded declarations, as well as their implementation.
 */
static void bad_mood_class_init  (BadMoodClass *klass);
static void bad_mood_init        (BadMood *badmood);

static GtkObjectClass *parent_class = NULL;

GtkType
bad_mood_get_type (void)
{
	static GtkType badmood_type = 0;

	if (!badmood_type) {
		static const GtkTypeInfo badmood_info = {
			"BadMood",
			sizeof (BadMood),
			sizeof (BadMoodClass),
			(GtkClassInitFunc) bad_mood_class_init,
			(GtkObjectInitFunc) bad_mood_init,
			/* reserved_1 */ NULL,
			/* reserved_2 */ NULL,
			(GtkClassInitFunc) NULL
		};

		badmood_type = bonobo_x_type_unique (
			BONOBO_X_OBJECT_TYPE,
			POA_Bonobo_Sample_BadMood__init,
			NULL,
			GTK_STRUCT_OFFSET (BadMoodClass, epv),
			&badmood_info);
	}
;	return badmood_type;
}

static void
bad_mood_class_init (BadMoodClass *klass)
{
	POA_Bonobo_Sample_BadMood__epv *epv = &klass->epv;
	parent_class = gtk_type_class (BONOBO_X_OBJECT_TYPE);

	/* TODO: more class initialization */

	/*
	 * TODO: place ptrs to member functions in epv
	 * ie. epv->my_func = my_obj_my_func;
	 */
	epv->say_hi = bad_mood_say_hi;
}

static void
bad_mood_init (BadMood *badmood)
{
	/* TODO: object initialization */
}

BadMood*
bad_mood_new (void)
{
	return gtk_type_new (bad_mood_get_type ());
}


/*
 * TODO: add your custom function implementations here
 */
CORBA_char*     
bad_mood_say_hi  (PortableServer_Servant _servant,
		  CORBA_Environment * ev)
{
	CORBA_string_dup ("Grmpff... stop bothering me!");
}

