# Code Generated by ZenTest v. 3.3.0
#                 classname: asrt / meth =  ratio%
# Rel::Server::TransactionManager:    0 /    6 =   0.00%
#     Rel::Server::Response:    0 /    2 =   0.00%
#          Rel::Server::Log:    0 /    2 =   0.00%
#  Rel::Server::Transaction:    0 /   11 =   0.00%
#               Rel::Server:    0 /    6 =   0.00%
#      Rel::Server::Request:    0 /    1 =   0.00%

require 'test/unit' unless defined? $ZENTEST and $ZENTEST

module TestRel
  class TestServer < Test::Unit::TestCase
    def test_do_run_command
      raise NotImplementedError, 'Need to write test_do_run_command'
    end

    def test_handle_request
      raise NotImplementedError, 'Need to write test_handle_request'
    end

    def test_read
      raise NotImplementedError, 'Need to write test_read'
    end

    def test_start
      raise NotImplementedError, 'Need to write test_start'
    end

    def test_write
      raise NotImplementedError, 'Need to write test_write'
    end
  end
end

module TestRel
  module TestServer
    class TestLog < Test::Unit::TestCase
      def test_class_exception
        raise NotImplementedError, 'Need to write test_class_exception'
      end

      def test_class_info
        raise NotImplementedError, 'Need to write test_class_info'
      end
    end
  end
end

module TestRel
  module TestServer
    class TestRequest < Test::Unit::TestCase
      def test_command
        raise NotImplementedError, 'Need to write test_command'
      end

      def test_command_equals
        raise NotImplementedError, 'Need to write test_command_equals'
      end

      def test_data
        raise NotImplementedError, 'Need to write test_data'
      end

      def test_data_equals
        raise NotImplementedError, 'Need to write test_data_equals'
      end

      def test_options
        raise NotImplementedError, 'Need to write test_options'
      end

      def test_options_equals
        raise NotImplementedError, 'Need to write test_options_equals'
      end
    end
  end
end

module TestRel
  module TestServer
    class TestResponse < Test::Unit::TestCase
      def test_data
        raise NotImplementedError, 'Need to write test_data'
      end

      def test_data_equals
        raise NotImplementedError, 'Need to write test_data_equals'
      end

      def test_options
        raise NotImplementedError, 'Need to write test_options'
      end

      def test_options_equals
        raise NotImplementedError, 'Need to write test_options_equals'
      end

      def test_response_chunk
        raise NotImplementedError, 'Need to write test_response_chunk'
      end

      def test_status
        raise NotImplementedError, 'Need to write test_status'
      end

      def test_status_equals
        raise NotImplementedError, 'Need to write test_status_equals'
      end
    end
  end
end

module TestRel
  module TestServer
    class TestTransaction < Test::Unit::TestCase
      def test__calling_elisp_eh
        raise NotImplementedError, 'Need to write test__calling_elisp_eh'
      end

      def test__id
        raise NotImplementedError, 'Need to write test__id'
      end

      def test__make_continuation
        raise NotImplementedError, 'Need to write test__make_continuation'
      end

      def test__pending_elisp
        raise NotImplementedError, 'Need to write test__pending_elisp'
      end

      def test__resume
        raise NotImplementedError, 'Need to write test__resume'
      end

      def test__ruby_eval
        raise NotImplementedError, 'Need to write test__ruby_eval'
      end

      def test__run
        raise NotImplementedError, 'Need to write test__run'
      end

      def test_call
        raise NotImplementedError, 'Need to write test_call'
      end

      def test_elisp
        raise NotImplementedError, 'Need to write test_elisp'
      end

      def test_elisp_bang
        raise NotImplementedError, 'Need to write test_elisp_bang'
      end
    end
  end
end

module TestRel
  module TestServer
    class TestTransactionManager < Test::Unit::TestCase
      def test_find
        raise NotImplementedError, 'Need to write test_find'
      end

      def test_forget
        raise NotImplementedError, 'Need to write test_forget'
      end

      def test_new_transaction
        raise NotImplementedError, 'Need to write test_new_transaction'
      end

      def test_remember
        raise NotImplementedError, 'Need to write test_remember'
      end
    end
  end
end

# Number of errors detected: 46
