(defun rotate-window-buffers ()
  (interactive)
  (let* ((ws (window-list))
         (bs (mapcar 'window-buffer ws))
         (ps (mapcar 'window-point ws))
         (w (pop ws)))
    (dolist (v (append ws `(,w)))
      (set-window-buffer v (pop bs))
      (set-window-point v (pop ps)))))
