;;;;;; Scheme-lookup: lookup documentation for Scheme symbols
;;;;;; Version $Version$

;;; This code is written by Trent W. Buck <trentbuck@gmail.com>
;;; (except where explicitly noted) and placed in the Public Domain.
;;; All warranties are disclaimed.

;;; This implementation uses the info version of Guile 1.6; it
;;; requires the info manual to be installed on your system.  On
;;; Debian, you can get it by apt-get installing the guile-1.6-doc
;;; package.

(require 'scheme-lookup)

(defun scheme-lookup-guile (symbol-name &optional redirect)
  (scheme-lookup-info "guile" (or redirect symbol-name)))

(put 'scheme-lookup-guile
     'scheme-lookup-pretty-name
     "Guile Reference Manual")

(mapc
 (lambda (x) (scheme-lookup-add-reference (list 'scheme-lookup-guile x)))
 '(;; procedures
   "$abs" "$acos" "$acosh" "$asin" "$asinh" "$atan" "$atan2" "$atanh"
   "$cos" "$cosh" "$exp" "$expt" "$log" "$sin" "$sinh" "$sqrt" "$tan"
   "$tanh" "%library-dir" "%make-void-port" "%package-data-dir"
   "%read-delimited!"  "%read-line" "%search-load-path" "%site-dir"
   "%thread-handler" "*" "*gh_scm2chars" "*gh_scm2doubles"
   "*gh_scm2floats" "*gh_scm2longs" "*gh_scm2newstr" "*gh_scm2shorts"
   "*gh_symbol2newstr" "+" "-" "->char-set" "/" "<" "<="
   "<group>-disable" "<group>-enable" "<group>-options" "<group>-set!"
   "=" ">" ">=" "abs" "accept" "access?"  "acons" "acos" "acosh"
   "add-hook!"  "advance-dfa!"  "alarm" "alist-cons" "alist-copy"
   "alist-delete" "alist-delete!"  "and" "angle" "any" "append"
   "append!"  "append-map" "append-map!"  "append-reverse"
   "append-reverse!"  "apply" "apply:nconc2last" "array->list"
   "array-contents" "array-copy!"  "array-copy-in-order!"
   "array-dimensions" "array-equal?"  "array-fill!"  "array-for-each"
   "array-in-bounds?"  "array-index-map!"  "array-map!"
   "array-map-in-order!"  "array-prototype" "array-rank" "array-ref"
   "array-set!"  "array-shape" "array?"  "ash" "asin" "asinh" "assoc"
   "assoc-ref" "assoc-remove!"  "assoc-set!"  "assq" "assq-ref"
   "assq-remove!"  "assq-set!"  "assv" "assv-ref" "assv-remove!"
   "assv-set!"  "async" "async-mark" "atan" "atanh" "backtrace"
   "basename" "batch-mode?"  "begin" "begin-thread" "bind" "bit-count"
   "bit-count*" "bit-extract" "bit-invert!"  "bit-position"
   "bit-set*!"  "boolean?"  "break" "break!"  "builtin-bindings"
   "caar" "cadr" "call-with-current-continuation"
   "call-with-dynamic-root" "call-with-input-file"
   "call-with-input-string" "call-with-new-thread"
   "call-with-output-file" "call-with-output-string"
   "call-with-values" "car" "car+cdr" "case" "catch" "cd" "cdddar"
   "cddddr" "cdr" "ceiling" "char->integer" "char-alphabetic?"
   "char-ci<=?"  "char-ci<?"  "char-ci=?"  "char-ci>=?"  "char-ci>?"
   "char-downcase" "char-is-both?"  "char-lower-case?"
   "char-numeric?"  "char-ready?"  "char-set" "char-set->list"
   "char-set->string" "char-set-adjoin" "char-set-adjoin!"
   "char-set-any" "char-set-complement" "char-set-complement!"
   "char-set-contains?"  "char-set-copy" "char-set-count"
   "char-set-cursor" "char-set-cursor-next" "char-set-delete"
   "char-set-delete!"  "char-set-diff+intersection"
   "char-set-diff+intersection!"  "char-set-difference"
   "char-set-difference!"  "char-set-every" "char-set-filter"
   "char-set-filter!"  "char-set-fold" "char-set-for-each"
   "char-set-hash" "char-set-intersection" "char-set-intersection!"
   "char-set-map" "char-set-ref" "char-set-size" "char-set-unfold"
   "char-set-unfold!"  "char-set-union" "char-set-union!"
   "char-set-xor" "char-set-xor!"  "char-set<=" "char-set="
   "char-set?"  "char-upcase" "char-upper-case?"  "char-whitespace?"
   "char<=?"  "char<?"  "char=?"  "char>=?"  "char>?"  "char?"
   "chdir" "chmod" "chown" "chroot" "circular-list" "circular-list?"
   "close" "close-all-ports-except" "close-fdes" "close-input-port"
   "close-output-port" "close-pipe" "close-port" "closedir" "closure?"
   "command-line" "compiled-regexp?"  "complex?"  "concatenate"
   "concatenate!"  "cond" "connect" "cons" "cons*" "cons-source"
   "copy-file" "copy-random-state" "copy-tree" "cos" "cosh" "crypt"
   "ctermid" "current-error-port" "current-input-port"
   "current-load-port" "current-output-port" "current-time" "cuserid"
   "debug-disable" "debug-enable" "debug-object?"  "debug-options"
   "debug-options-interface" "debug-set!"  "define" "define*"
   "define*-public" "define-macro" "define-module" "define-public"
   "define-reader-ctor" "defined?"  "defmacro" "defmacro*"
   "defmacro*-public" "delete" "delete!"  "delete-duplicates"
   "delete-duplicates!"  "delete-file" "delete1!"  "delq" "delq!"
   "delq1!"  "delv" "delv!"  "delv1!"  "destroy-guardian!"
   "dfa-continuable?"  "dfa-final-tag" "dfa-fork"
   "dimensions->uniform-array" "directory-stream?"  "dirname"
   "display" "display-application" "display-backtrace" "display-error"
   "do" "dotted-list?"  "doubly-weak-hash-table?"  "drain-input"
   "drop" "drop-right" "drop-right!"  "drop-while" "dup" "dup->fdes"
   "dup->inport" "dup->outport" "dup->port" "dup2" "duplicate-port"
   "dynamic-args-call" "dynamic-call" "dynamic-func" "dynamic-link"
   "dynamic-object?"  "dynamic-root" "dynamic-unlink" "dynamic-wind"
   "effective-version" "eighth" "enclose-array" "end-of-char-set?"
   "endgrent" "endhostent" "endnetent" "endprotoent" "endpwent"
   "endservent" "entity?"  "environ" "eof-object?"  "eq?"  "equal?"
   "eqv?"  "error" "eval" "eval-disable" "eval-enable" "eval-options"
   "eval-options-interface" "eval-set!"  "eval-string" "eval2"
   "evaluator-traps-interface" "even?"  "every" "exact->inexact"
   "exact?"  "execl" "execle" "execlp" "exp" "expect" "expect-strings"
   "export" "expt" "false-if-exception" "fchmod" "fchown" "fcntl"
   "fdes->inport" "fdes->outport" "fdes->ports" "fdopen" "feature?"
   "fflush" "fifth" "file-port?"  "fileno" "filter" "filter!"
   "filter-map" "find" "find-tail" "first" "flock" "floor" "fluid-ref"
   "fluid-set!"  "fluid?"  "flush-all-ports" "fn" "fold" "fold-right"
   "for-each" "force" "force-output" "format" "fourth"
   "frame-arguments" "frame-evaluating-args?"  "frame-next"
   "frame-number" "frame-overflow?"  "frame-previous"
   "frame-procedure" "frame-procedure?"  "frame-real?"  "frame-source"
   "frame?"  "fstat" "fsync" "ftell" "ftruncate" "gc" "gc-stats" "gcd"
   "gensym" "gentemp" "get-internal-real-time" "get-internal-run-time"
   "get-output-string" "get-print-state" "getcwd" "getegid" "getenv"
   "geteuid" "getgid" "getgr" "getgrent" "getgrgid" "getgrnam"
   "getgroups" "gethost" "gethostbyaddr" "gethostbyname" "gethostent"
   "gethostname" "getitimer" "getlogin" "getnet" "getnetbyaddr"
   "getnetbyname" "getnetent" "getopt-long" "getpass" "getpeername"
   "getpgrp" "getpid" "getppid" "getpriority" "getproto"
   "getprotobyname" "getprotobynumber" "getprotoent" "getpw"
   "getpwent" "getpwnam" "getpwuid" "getserv" "getservbyname"
   "getservbyport" "getservent" "getsockname" "getsockopt"
   "gettimeofday" "getuid" "GH_ALLOW_INTS" "gh_append" "gh_append2"
   "gh_append3" "gh_append4" "gh_apply" "gh_assoc" "gh_assq" "gh_assv"
   "gh_bool2scm" "gh_boolean_p" "gh_c" "gh_call0" "gh_call1"
   "gh_call2" "gh_call3" "gh_car" "gh_catch" "gh_cdr" "gh_char2scm"
   "gh_char_p" "gh_chars2byvect" "gh_cons" "GH_DEFER_INTS" "gh_define"
   "gh_double2scm" "gh_doubles2dvect" "gh_doubles2scm" "gh_enter"
   "gh_eq_p" "gh_equal_p" "gh_eqv_p" "gh_eval_file" "gh_eval_str"
   "gh_exact_p" "gh_floats2fvect" "gh_get_substr" "gh_inexact_p"
   "gh_ints2scm" "gh_is_eq" "gh_is_equal" "gh_is_eqv" "gh_length"
   "gh_list" "gh_list_p" "gh_list_ref" "gh_list_tail"
   "gh_list_to_vector" "gh_load" "gh_long2scm" "gh_longs2ivect"
   "gh_make_vector" "gh_member" "gh_memq" "gh_memv" "gh_new_procedure"
   "gh_null_p" "gh_obj_length" "gh_pair_p" "gh_procedure_p" "gh_repl"
   "gh_reverse" "gh_scm2bool" "gh_scm2char" "gh_scm2double"
   "gh_scm2long" "gh_scm2ulong" "gh_set_car_x" "gh_set_cdr_x"
   "gh_set_substr" "gh_shorts2svect" "gh_str02scm" "gh_str2scm"
   "gh_string_equal_p" "gh_symbol2scm" "gh_symbol_p" "gh_throw"
   "gh_ulong2scm" "gh_ulongs2uvect" "gh_vector" "gh_vector_length"
   "gh_vector_p" "gh_vector_ref" "gh_vector_set" "gmtime"
   "guardian-destroyed?"  "guardian-greedy?"  "GUILE_CHECK_RETVAL"
   "GUILE_FLAGS" "GUILE_MODULE_AVAILABLE" "GUILE_MODULE_CHECK"
   "GUILE_MODULE_EXPORTS" "GUILE_MODULE_REQUIRED"
   "GUILE_MODULE_REQUIRED_EXPORT" "GUILE_PROGS" "GUILE_SITE_DIR"
   "hash" "hash-create-handle!"  "hash-fold" "hash-get-handle"
   "hash-ref" "hash-remove!"  "hash-set!"  "hashq"
   "hashq-create-handle!"  "hashq-get-handle" "hashq-ref"
   "hashq-remove!"  "hashq-set!"  "hashv" "hashv-create-handle!"
   "hashv-get-handle" "hashv-ref" "hashv-remove!"  "hashv-set!"
   "hashx-create-handle!"  "hashx-get-handle" "hashx-ref" "hashx-set!"
   "hook->list" "hook-empty?"  "hook?"  "hostent:addr-list"
   "hostent:addrtype" "hostent:aliases" "hostent:length"
   "hostent:name" "htonl" "htons" "if" "imag-part" "inet-aton"
   "inet-lnaof" "inet-makeaddr" "inet-netof" "inet-ntoa" "inet-ntop"
   "inet-pton" "inexact->exact" "inexact?"  "input-port?"
   "integer->char" "integer-expt" "integer-length" "integer?"
   "interaction-environment" "intern-symbol" "iota" "isatty?"
   "join-thread" "key" "keyword->symbol" "keyword-dash-symbol"
   "keyword?"  "kill" "lambda" "lambda*" "last" "last-pair"
   "last-stack-frame" "lazy-catch" "lchown" "lcm" "length" "length+"
   "let" "let*" "let-keywords" "let-optional" "let-optional*" "letrec"
   "link" "list" "list->char-set" "list->char-set!"  "list->string"
   "list->TAGvector" "list->uniform-array" "list->uniform-vector"
   "list->vector" "list->weak-vector" "list-cdr-ref" "list-cdr-set!"
   "list-copy" "list-head" "list-index" "list-ref" "list-set!"
   "list-tabulate" "list-tail" "list=" "list?"  "listen" "load"
   "load-extension" "load-from-path" "local-eval" "localtime"
   "lock-mutex" "log" "log10" "logand" "logbit?"  "logcount" "logior"
   "lognot" "logtest" "logxor" "lset-adjoin" "lset-adjoin!"
   "lset-diff+intersection" "lset-diff+intersection!"
   "lset-difference" "lset-difference!"  "lset-intersection"
   "lset-intersection!"  "lset-union" "lset-union!"  "lset-xor"
   "lset-xor!"  "lset<=" "lset=" "lstat" "macro-name"
   "macro-transformer" "macro-type" "macro?"  "magnitude" "main_prog"
   "major-version" "make-arbiter" "make-array" "make-class-object"
   "make-condition-variable" "make-doubly-weak-hash-table"
   "make-fluid" "make-guardian" "make-hash-table" "make-hook"
   "make-keyword-from-dash-symbol" "make-list" "make-mutex"
   "make-object-property" "make-polar" "make-procedure-with-setter"
   "make-record-type" "make-rectangular" "make-regexp"
   "make-shared-array" "make-shared-substring" "make-soft-port"
   "make-stack" "make-string" "make-struct" "make-struct-layout"
   "make-subclass-object" "make-TAGvector" "make-thread"
   "make-undefined-variable" "make-uniform-array"
   "make-uniform-vector" "make-variable" "make-vector"
   "make-vtable-vtable" "make-weak-key-hash-table"
   "make-weak-value-hash-table" "make-weak-vector" "malloc-stats"
   "map" "map!"  "map-in-order" "mask-signals" "match:count"
   "match:end" "match:prefix" "match:start" "match:string"
   "match:substring" "match:suffix" "max" "member"
   "memoized-environment" "memoized?"  "memq" "memv" "merge" "merge!"
   "micro-version" "min" "minor-version" "mkdir" "mknod" "mkstemp!"
   "mktime" "modulo" "monitor" "move->fdes" "negative?"
   "netent:addrtype" "netent:aliases" "netent:name" "netent:net"
   "newline" "nice" "nil-car" "nil-cdr" "nil-cons" "nil-eq" "ninth"
   "noop" "not" "not-pair?"  "ntohl" "ntohs" "null" "null-environment"
   "null-list?"  "null?"  "number->string" "number?"  "object->string"
   "object-address" "object-properties" "object-property" "odd?"
   "open" "open-fdes" "open-file" "open-input-file" "open-input-pipe"
   "open-input-string" "open-output-file" "open-output-pipe"
   "open-output-string" "open-pipe" "opendir" "operator?"
   "option-ref" "or" "output-port?"  "pair-fold" "pair-fold-right"
   "pair-for-each" "pair?"  "parse-path" "partition" "partition!"
   "pause" "pclose" "peek-char" "pipe" "popen" "port->fdes"
   "port-closed?"  "port-column" "port-filename" "port-for-each"
   "port-line" "port-mode" "port-revealed" "port-with-print-state"
   "port?"  "positive?"  "pretty-print" "primitive-eval"
   "primitive-exit" "primitive-fork" "primitive-load"
   "primitive-load-path" "primitive-make-property"
   "primitive-move->fdes" "primitive-property-del!"
   "primitive-property-ref" "primitive-property-set!"  "print-disable"
   "print-enable" "print-options" "print-options-interface"
   "print-set!"  "procedure" "procedure->macro"
   "procedure->memoizing-macro" "procedure->syntax"
   "procedure-documentation" "procedure-environment" "procedure-name"
   "procedure-properties" "procedure-property" "procedure-source"
   "procedure-with-setter?"  "procedure?"  "program-arguments"
   "promise?"  "proper-list?"  "protoent:aliases" "protoent:name"
   "protoent:proto" "provide" "provided?"  "PTR2SCM" "putenv" "pwd"
   "quit" "quotient" "raise" "random" "random:exp"
   "random:hollow-sphere!"  "random:normal" "random:normal-vector!"
   "random:solid-sphere!"  "random:uniform" "rational?"  "read"
   "read-and-eval!"  "read-char" "read-delimited" "read-delimited!"
   "read-disable" "read-enable" "read-hash-extend" "read-line"
   "read-line!"  "read-only-string?"  "read-options"
   "read-options-interface" "read-set!"  "read-string!/partial"
   "readdir" "readlink" "real-part" "real?"  "receive"
   "record-accessor" "record-constructor" "record-modifier"
   "record-predicate" "record-type-descriptor" "record-type-fields"
   "record-type-name" "record?"  "recv!"  "recvfrom!"  "redirect-port"
   "reduce" "reduce-right" "regcomp" "regexec" "regexp->dfa"
   "regexp-exec" "regexp-match?"  "regexp-quote" "regexp-substitute"
   "regexp-substitute/global" "regexp?"  "release-arbiter"
   "release-port-handle" "remainder" "remove" "remove!"
   "remove-hook!"  "rename" "rename-file" "reset-dfa!"  "reset-hook!"
   "restore-signals" "restricted-vector-sort!"  "reverse" "reverse!"
   "reverse-list->string" "rewinddir" "rmdir" "round" "run-asyncs"
   "run-hook" "scheme-report-environment" "scm-error" "SCM2PTR"
   "scm_abs" "scm_accept" "scm_access" "scm_acons" "scm_acosh"
   "scm_add_feature" "scm_add_hook_x" "scm_alarm" "scm_append"
   "scm_append_x" "SCM_ARG1" "SCM_ARG2" "SCM_ARG3" "SCM_ARG4"
   "SCM_ARG5" "SCM_ARG6" "SCM_ARG7" "SCM_ARGn" "scm_array_contents"
   "scm_array_copy_x" "scm_array_dimensions" "scm_array_fill_x"
   "scm_array_for_each" "scm_array_in_bounds_p"
   "scm_array_index_map_x" "scm_array_map_x" "scm_array_p"
   "scm_array_prototype" "scm_array_rank" "scm_array_set_x"
   "scm_array_to_list" "scm_ash" "scm_asinh" "SCM_ASSERT" "scm_assoc"
   "scm_assoc_ref" "scm_assoc_remove_x" "scm_assoc_set_x" "scm_assq"
   "scm_assq_ref" "scm_assq_remove_x" "scm_assq_set_x" "scm_assv"
   "scm_assv_ref" "scm_assv_remove_x" "scm_assv_set_x" "scm_async"
   "scm_async_mark" "scm_atanh" "scm_backtrace" "scm_basename"
   "scm_bind" "scm_bit_count" "scm_bit_count_star" "scm_bit_extract"
   "scm_bit_invert_x" "scm_bit_position" "scm_bit_set_star_x"
   "SCM_BOOL_F" "SCM_BOOL_NOT" "SCM_BOOL_T" "scm_boolean_p"
   "scm_boot_guile" "scm_builtin_bindings"
   "scm_c_call_with_current_module" "scm_c_define"
   "scm_c_define_gsubr" "scm_c_define_module" "scm_c_export"
   "scm_c_hook_add" "scm_c_hook_init" "scm_c_hook_remove"
   "scm_c_load_extension" "scm_c_lookup" "scm_c_module_define"
   "scm_c_module_lookup" "scm_c_register_extension"
   "scm_c_resolve_module" "scm_c_run_hook" "scm_c_use_module"
   "SCM_CAAR" "SCM_CADR" "scm_call_with_dynamic_root"
   "scm_call_with_input_string" "scm_call_with_output_string"
   "SCM_CAR" "scm_catch" "SCM_CDAR" "SCM_CDDDDR" "SCM_CDR"
   "SCM_CELL_OBJECT" "SCM_CELL_TYPE" "SCM_CELL_WORD" "SCM_CHAR"
   "scm_char_alphabetic_p" "scm_char_downcase" "scm_char_is_both_p"
   "scm_char_lower_case_p" "scm_char_numeric_p" "scm_char_p"
   "scm_char_ready_p" "scm_char_to_integer" "scm_char_upcase"
   "scm_char_upper_case_p" "scm_char_whitespace_p" "SCM_CHARP"
   "scm_chdir" "scm_chmod" "scm_chown" "scm_chroot" "scm_close"
   "scm_close_all_ports_except" "scm_close_fdes"
   "scm_close_input_port" "scm_close_output_port" "scm_close_port"
   "scm_closedir" "scm_closure_p" "SCM_CLOSUREP" "SCM_CODE"
   "scm_connect" "scm_cons" "scm_cons_source" "scm_cons_star"
   "SCM_CONSP" "scm_copy_file" "scm_copy_random_state" "scm_copy_tree"
   "scm_crypt" "scm_ctermid" "scm_current_error_port"
   "scm_current_input_port" "scm_current_load_port"
   "scm_current_module" "scm_current_output_port" "scm_current_time"
   "scm_cuserid" "scm_debug_object_p" "scm_debug_options" "scm_define"
   "scm_definedp" "scm_delete" "scm_delete1_x" "scm_delete_file"
   "scm_delete_x" "scm_delq" "scm_delq1_x" "scm_delq_x" "scm_delv"
   "scm_delv1_x" "scm_delv_x" "scm_destroy_guardian_x"
   "scm_dimensions_to_uniform_array" "scm_directory_stream_p"
   "scm_dirname" "scm_display_application" "scm_display_backtrace"
   "scm_display_error" "scm_doubly_weak_hash_table_p"
   "scm_drain_input" "scm_dup2" "scm_dup_to_fdes"
   "scm_dynamic_args_call" "scm_dynamic_call" "scm_dynamic_func"
   "scm_dynamic_link" "scm_dynamic_object_p" "scm_dynamic_root"
   "scm_dynamic_unlink" "scm_dynamic_wind" "scm_effective_version"
   "scm_enclose_array" "scm_entity_p" "SCM_ENV" "scm_environ"
   "scm_eof_object_p" "SCM_EOF_VAL" "SCM_EOL" "scm_error_scm"
   "scm_eval" "scm_eval2" "scm_eval_options_interface"
   "scm_eval_string" "scm_evaluator_traps" "scm_even_p" "scm_exact_p"
   "scm_execl" "scm_execle" "scm_execlp" "scm_fcntl"
   "scm_fdes_to_ports" "scm_fdopen" "scm_file_port_p" "scm_fileno"
   "scm_flock" "scm_fluid_p" "scm_fluid_ref" "scm_fluid_set_x"
   "scm_flush_all_ports" "scm_force" "scm_force_output" "scm_fork"
   "scm_frame_arguments" "scm_frame_evaluating_args_p"
   "scm_frame_next" "scm_frame_number" "scm_frame_overflow_p"
   "scm_frame_p" "scm_frame_previous" "scm_frame_procedure"
   "scm_frame_procedure_p" "scm_frame_real_p" "scm_frame_source"
   "scm_free0" "scm_fsync" "scm_ftell" "scm_gc" "scm_gc_mark"
   "scm_gc_stats" "scm_gensym" "scm_gentemp"
   "scm_get_internal_real_time" "scm_get_internal_run_time"
   "scm_get_output_string" "scm_get_print_state" "scm_getcwd"
   "scm_getegid" "scm_getenv" "scm_geteuid" "scm_getgid"
   "scm_getgrgid" "scm_getgroups" "scm_gethost" "scm_gethostname"
   "scm_getitimer" "scm_getlogin" "scm_getnet" "scm_getpass"
   "scm_getpeername" "scm_getpgrp" "scm_getpid" "scm_getppid"
   "scm_getpriority" "scm_getproto" "scm_getpwuid" "scm_getserv"
   "scm_getsockname" "scm_getsockopt" "scm_gettimeofday" "scm_getuid"
   "scm_gmtime" "scm_guardian_destroyed_p" "scm_guardian_greedy_p"
   "scm_hash" "scm_hash_create_handle_x" "scm_hash_fold"
   "scm_hash_get_handle" "scm_hash_ref" "scm_hash_remove_x"
   "scm_hash_set_x" "scm_hashq" "scm_hashq_create_handle_x"
   "scm_hashq_get_handle" "scm_hashq_ref" "scm_hashq_remove_x"
   "scm_hashq_set_x" "scm_hashv" "scm_hashv_create_handle_x"
   "scm_hashv_get_handle" "scm_hashv_ref" "scm_hashv_remove_x"
   "scm_hashv_set_x" "scm_hashx_create_handle_x"
   "scm_hashx_get_handle" "scm_hashx_ref" "scm_hashx_set_x"
   "scm_hook_empty_p" "scm_hook_p" "scm_hook_to_list" "SCM_HOOKP"
   "scm_htonl" "scm_htons" "SCM_IMP" "scm_inet_aton"
   "scm_inet_makeaddr" "scm_inet_netof" "scm_inet_ntoa"
   "scm_inet_ntop" "scm_inet_pton" "scm_inexact_p"
   "scm_inexact_to_exact" "scm_init_guile" "scm_input_port_p"
   "scm_integer_expt" "scm_integer_length" "scm_integer_p"
   "scm_integer_to_char" "scm_interaction_environment"
   "scm_intern_symbol" "SCM_INUM" "SCM_INUMP" "scm_isatty_p"
   "scm_keyword_dash_symbol" "scm_keyword_p" "scm_kill"
   "scm_last_pair" "scm_last_stack_frame" "scm_lazy_catch"
   "scm_length" "scm_link" "scm_list" "scm_list_cdr_set_x"
   "scm_list_copy" "scm_list_head" "scm_list_p" "scm_list_ref"
   "scm_list_set_x" "scm_list_tail" "scm_list_to_uniform_array"
   "scm_listen" "scm_lnaof" "scm_load_extension" "scm_local_eval"
   "scm_localtime" "scm_logbit_p" "scm_logcount" "scm_lognot"
   "scm_logtest" "scm_lookup" "scm_lstat" "scm_macro_name"
   "scm_macro_p" "scm_macro_transformer" "scm_macro_type"
   "scm_major_version" "scm_makacro" "scm_make_arbiter"
   "SCM_MAKE_CHAR" "scm_make_class_object"
   "scm_make_doubly_weak_hash_table" "scm_make_fluid"
   "scm_make_guardian" "scm_make_hook"
   "scm_make_keyword_from_dash_symbol" "scm_make_polar"
   "scm_make_procedure_with_setter" "scm_make_rectangular"
   "scm_make_regexp" "scm_make_shared_array"
   "scm_make_shared_substring" "scm_make_smob_type"
   "scm_make_smob_type_mfpe" "scm_make_soft_port" "scm_make_stack"
   "scm_make_string" "scm_make_struct" "scm_make_struct_layout"
   "scm_make_subclass_object" "scm_make_undefined_variable"
   "scm_make_variable" "scm_make_vector" "scm_make_vtable_vtable"
   "scm_make_weak_key_hash_table" "scm_make_weak_value_hash_table"
   "scm_make_weak_vector" "SCM_MAKINUM" "scm_makmacro" "scm_makmmacro"
   "scm_map" "scm_markcdr" "scm_mask_signals" "scm_member"
   "scm_memoized_environment" "scm_memoized_p" "scm_memq" "scm_memv"
   "scm_merge" "scm_merge_x" "scm_micro_version" "scm_minor_version"
   "scm_mkdir" "scm_mknod" "scm_mkstemp" "scm_mktime"
   "scm_module_define" "scm_module_lookup" "scm_module_reverse_lookup"
   "scm_must_free" "scm_must_malloc" "scm_must_realloc"
   "scm_nconc2last" "SCM_NCONSP" "SCM_NEWCELL" "scm_newline"
   "SCM_NEWSMOB" "SCM_NEWSMOB2" "SCM_NEWSMOB3" "SCM_NFALSEP"
   "scm_nice" "scm_nil_car" "scm_nil_cdr" "scm_nil_cons" "SCM_NIMP"
   "SCM_NINUMP" "scm_noop" "scm_not" "scm_ntohl" "scm_ntohs"
   "scm_null" "scm_null_p" "scm_number_p" "scm_number_to_string"
   "scm_object_address" "scm_object_properties" "scm_object_property"
   "scm_object_to_string" "scm_odd_p" "scm_open" "scm_open_fdes"
   "scm_open_file" "scm_open_input_string" "scm_open_output_string"
   "scm_opendir" "scm_operator_p" "scm_output_port_p" "SCM_PACK"
   "scm_pair_p" "scm_parse_path" "scm_pause" "scm_peek_char"
   "scm_pipe" "scm_port_closed_p" "scm_port_column"
   "scm_port_filename" "scm_port_for_each" "scm_port_line"
   "scm_port_mode" "scm_port_p" "scm_port_revealed"
   "scm_port_with_print_state" "scm_primitive_eval"
   "scm_primitive_exit" "scm_primitive_load" "scm_primitive_load_path"
   "scm_primitive_make_property" "scm_primitive_move_to_fdes"
   "scm_primitive_property_del_x" "scm_primitive_property_ref"
   "scm_primitive_property_set_x" "scm_print_options" "scm_procedure"
   "scm_procedure_documentation" "scm_procedure_environment"
   "scm_procedure_name" "scm_procedure_p" "scm_procedure_properties"
   "scm_procedure_property" "scm_procedure_source"
   "scm_procedure_with_setter_p" "SCM_PROCPROPS"
   "scm_program_arguments" "scm_promise_p" "scm_putenv" "scm_raise"
   "scm_random" "scm_random_exp" "scm_random_hollow_sphere_x"
   "scm_random_normal" "scm_random_normal_vector_x"
   "scm_random_solid_sphere_x" "scm_random_uniform" "scm_read"
   "scm_read_and_eval_x" "scm_read_char" "scm_read_delimited_x"
   "scm_read_hash_extend" "scm_read_line" "scm_read_only_string_p"
   "scm_read_options" "scm_read_string_x_partial" "scm_readdir"
   "scm_readlink" "scm_real_p" "scm_recv" "scm_recvfrom"
   "scm_redirect_port" "scm_regexp_exec" "scm_regexp_p"
   "scm_release_arbiter" "scm_remove_hook_x" "scm_rename"
   "scm_reset_hook_x" "scm_resolve_module" "scm_restore_signals"
   "scm_restricted_vector_sort_x" "SCM_RETURN_NEWSMOB"
   "SCM_RETURN_NEWSMOB2" "SCM_RETURN_NEWSMOB3" "scm_reverse"
   "scm_reverse_x" "scm_rewinddir" "scm_rmdir" "scm_round"
   "scm_run_asyncs" "scm_run_hook" "scm_search_path"
   "scm_seed_to_random_state" "scm_seek" "scm_select" "scm_send"
   "scm_sendto" "scm_set_car_x" "scm_set_cdr_x" "SCM_SET_CELL_OBJECT"
   "SCM_SET_CELL_TYPE" "SCM_SET_CELL_WORD"
   "scm_set_current_error_port" "scm_set_current_input_port"
   "scm_set_current_module" "scm_set_current_output_port"
   "scm_set_object_procedure_x" "scm_set_object_properties_x"
   "scm_set_object_property_x" "scm_set_port_column_x"
   "scm_set_port_filename_x" "scm_set_port_line_x"
   "scm_set_port_revealed_x" "scm_set_procedure_properties_x"
   "scm_set_procedure_property_x" "scm_set_smob_equalp"
   "scm_set_smob_free" "scm_set_smob_mark" "scm_set_smob_print"
   "scm_set_source_properties_x" "scm_set_source_property_x"
   "scm_set_struct_vtable_name_x" "SCM_SETCAR" "SCM_SETCDR"
   "scm_setegid" "scm_seteuid" "scm_setgid" "scm_setgrent"
   "scm_sethost" "scm_sethostname" "scm_setitimer" "scm_setlocale"
   "scm_setnet" "scm_setpgid" "scm_setpriority" "SCM_SETPROCPROPS"
   "scm_setproto" "scm_setpwent" "scm_setserv" "scm_setsid"
   "scm_setsockopt" "scm_setuid" "scm_setvbuf"
   "scm_shared_array_increments" "scm_shared_array_offset"
   "scm_shared_array_root" "scm_shell" "scm_shutdown" "scm_sigaction"
   "scm_simple_format" "scm_sleep" "scm_sloppy_assoc"
   "scm_sloppy_assq" "scm_sloppy_assv" "scm_sloppy_member"
   "scm_sloppy_memq" "scm_sloppy_memv" "SCM_SNAME" "SCM_SNARF_INIT"
   "scm_socket" "scm_socketpair" "scm_sort" "scm_sort_list"
   "scm_sort_list_x" "scm_sort_x" "scm_sorted_p"
   "scm_source_properties" "scm_source_property" "scm_stable_sort"
   "scm_stable_sort_x" "scm_stack_id" "scm_stack_length" "scm_stack_p"
   "scm_stack_ref" "scm_stat" "scm_status_exit_val"
   "scm_status_stop_sig" "scm_status_term_sig" "scm_strerror"
   "scm_strftime" "scm_string" "scm_string_append"
   "scm_string_capitalize" "scm_string_capitalize_x"
   "SCM_STRING_CHARS" "scm_string_ci_to_symbol" "scm_string_copy"
   "scm_string_downcase" "scm_string_downcase_x" "scm_string_fill_x"
   "scm_string_index" "scm_string_length" "SCM_STRING_LENGTH"
   "scm_string_null_p" "scm_string_p" "scm_string_ref"
   "scm_string_rindex" "scm_string_set_x" "scm_string_split"
   "scm_string_to_list" "scm_string_to_number"
   "scm_string_to_obarray_symbol" "scm_string_to_symbol"
   "scm_string_upcase" "scm_string_upcase_x" "SCM_STRINGP"
   "scm_strptime" "scm_struct_p" "scm_struct_ref" "scm_struct_set_x"
   "scm_struct_vtable" "scm_struct_vtable_name" "scm_struct_vtable_p"
   "scm_struct_vtable_tag" "scm_substring" "scm_substring_fill_x"
   "scm_substring_move_x" "scm_symbol_binding" "scm_symbol_bound_p"
   "SCM_SYMBOL_CHARS" "scm_symbol_fref" "scm_symbol_fset_x"
   "scm_symbol_hash" "scm_symbol_interned_p" "SCM_SYMBOL_LENGTH"
   "scm_symbol_p" "scm_symbol_pref" "scm_symbol_pset_x"
   "scm_symbol_set_x" "scm_symbol_to_string" "SCM_SYMBOLP"
   "scm_symlink" "scm_sync" "scm_sys_atan2" "scm_sys_expt"
   "scm_sys_library_dir" "scm_sys_make_void_port"
   "scm_sys_package_data_dir" "scm_sys_search_load_path"
   "scm_sys_site_dir" "scm_system" "scm_system_async"
   "scm_system_async_mark" "scm_tcgetpgrp" "scm_tcsetpgrp" "scm_throw"
   "scm_thunk_p" "scm_times" "scm_tmpnam" "scm_transpose_array"
   "scm_truncate" "scm_truncate_file" "scm_try_arbiter" "scm_ttyname"
   "scm_tzset" "scm_umask" "scm_uname" "SCM_UNBNDP" "SCM_UNDEFINED"
   "scm_uniform_array_read_x" "scm_uniform_array_write"
   "scm_uniform_vector_length" "scm_uniform_vector_ref"
   "scm_unintern_symbol" "scm_unmask_signals" "scm_unmemoize"
   "SCM_UNPACK" "scm_unread_char" "scm_unread_string"
   "SCM_UNSPECIFIED" "scm_usleep" "scm_utime" "scm_values"
   "scm_variable_bound_p" "scm_variable_p" "scm_variable_ref"
   "scm_variable_set_x" "scm_vector" "SCM_VECTOR_BASE"
   "scm_vector_fill_x" "scm_vector_length" "SCM_VECTOR_LENGTH"
   "scm_vector_move_left_x" "scm_vector_move_right_x" "scm_vector_p"
   "scm_vector_ref" "scm_vector_set_x" "scm_vector_to_list"
   "SCM_VECTORP" "scm_version" "scm_waitpid"
   "scm_weak_key_hash_table_p" "scm_weak_value_hash_table_p"
   "scm_weak_vector" "scm_weak_vector_p" "scm_with_fluids"
   "scm_with_traps" "scm_write_char" "scm_write_line"
   "scm_write_string_partial" "search-path" "second"
   "seed->random-state" "seek" "select" "send" "sendto"
   "servent:aliases" "servent:name" "servent:port" "servent:proto"
   "set-batch-mode?!"  "set-car!"  "set-cdr!"
   "set-current-error-port" "set-current-input-port"
   "set-current-output-port" "set-object-procedure!"
   "set-object-properties!"  "set-object-property!"
   "set-port-column!"  "set-port-filename!"  "set-port-line!"
   "set-port-revealed!"  "set-procedure-properties!"
   "set-procedure-property!"  "set-source-properties!"
   "set-source-property!"  "set-struct-vtable-name!"
   "set-symbol-property!"  "setegid" "setenv" "seteuid" "setgid"
   "setgr" "setgrent" "sethost" "sethostent" "sethostname" "setitimer"
   "setlocale" "setnet" "setnetent" "setpgid" "setpriority" "setproto"
   "setprotoent" "setpw" "setpwent" "setserv" "setservent" "setsid"
   "setsockopt" "setter" "setuid" "setvbuf" "seventh"
   "shared-array-increments" "shared-array-offset" "shared-array-root"
   "shutdown" "sigaction" "signal-condition-variable" "simple-format"
   "sin" "sinh" "sixth" "sleep" "sloppy-assoc" "sloppy-assq"
   "sloppy-assv" "sloppy-member" "sloppy-memq" "sloppy-memv" "socket"
   "socketpair" "sort" "sort!"  "sort-list" "sort-list!"  "sorted?"
   "source-properties" "source-property" "span" "span!"  "split-at"
   "split-at!"  "sqrt" "stable-sort" "stable-sort!"  "stack-id"
   "stack-length" "stack-ref" "stack?"  "start-stack" "stat"
   "status:exit-val" "status:stop-sig" "status:term-sig" "strerror"
   "strftime" "string" "string->char-set" "string->char-set!"
   "string->list" "string->number" "string->obarray-symbol"
   "string->symbol" "string-any" "string-append"
   "string-append/shared" "string-capitalize" "string-capitalize!"
   "string-ci->symbol" "string-ci<" "string-ci<=" "string-ci<=?"
   "string-ci<>" "string-ci<?"  "string-ci=" "string-ci=?"
   "string-ci>" "string-ci>=" "string-ci>=?"  "string-ci>?"
   "string-compare" "string-compare-ci" "string-concatenate"
   "string-concatenate-reverse" "string-concatenate-reverse/shared"
   "string-concatenate/shared" "string-contains" "string-contains-ci"
   "string-copy" "string-copy!"  "string-count" "string-delete"
   "string-downcase" "string-downcase!"  "string-drop"
   "string-drop-right" "string-every" "string-fill!"  "string-filter"
   "string-fold" "string-fold-right" "string-for-each" "string-hash"
   "string-hash-ci" "string-index" "string-index-right" "string-join"
   "string-length" "string-map" "string-map!"  "string-match"
   "string-null?"  "string-pad" "string-pad-right" "string-prefix-ci?"
   "string-prefix-length" "string-prefix-length-ci" "string-prefix?"
   "string-ref" "string-replace" "string-reverse" "string-reverse!"
   "string-rindex" "string-set!"  "string-skip" "string-skip-right"
   "string-split" "string-suffix-ci?"  "string-suffix-length"
   "string-suffix-length-ci" "string-suffix?"  "string-tabulate"
   "string-take" "string-take-right" "string-titlecase"
   "string-titlecase!"  "string-tokenize" "string-trim"
   "string-trim-both" "string-trim-right" "string-unfold"
   "string-unfold-right" "string-upcase" "string-upcase!"
   "string-xcopy!"  "string<" "string<=" "string<=?"  "string<>"
   "string<?"  "string=" "string=?"  "string>" "string>=" "string>=?"
   "string>?"  "string?"  "strptime" "struct-ref" "struct-set!"
   "struct-vtable" "struct-vtable-name" "struct-vtable-tag"
   "struct-vtable?"  "struct?"  "substring" "substring-fill!"
   "substring-move!"  "substring/shared" "symbol->keyword"
   "symbol->string" "symbol-binding" "symbol-bound?"  "symbol-fref"
   "symbol-fset!"  "symbol-hash" "symbol-interned?"  "symbol-pref"
   "symbol-prefix-proc" "symbol-property" "symbol-property-remove!"
   "symbol-pset!"  "symbol-set!"  "symbol?"  "symlink" "sync" "system"
   "system-async" "system-async-mark" "TAGvector" "TAGvector->list"
   "TAGvector-length" "TAGvector-ref" "TAGvector?"  "take" "take!"
   "take-right" "take-while" "take-while!"  "tan" "tanh" "tcgetpgrp"
   "tcsetpgrp" "tenth" "third" "throw" "thunk?"  "times" "tmpnam"
   "trace" "transpose-array" "trap-disable" "trap-enable" "trap-set!"
   "traps" "truncate" "truncate-file" "try-arbiter" "ttyname" "tzset"
   "uce-range->char-set!"  "ucs-range->char-set" "umask" "uname"
   "unfold" "unfold-right" "unhash-name" "uniform-array-read!"
   "uniform-array-set1!"  "uniform-array-write" "uniform-vector-fill!"
   "uniform-vector-length" "uniform-vector-read!"
   "uniform-vector-ref" "uniform-vector-write" "unintern-symbol"
   "unlink" "unlock-mutex" "unmask-signals" "unmemoize" "unread-char"
   "unread-string" "untrace" "unzip1" "unzip2" "unzip3" "unzip4"
   "unzip5" "use-modules" "use-syntax" "usleep" "utime" "values"
   "variable-bound?"  "variable-ref" "variable-set!"  "variable?"
   "vector" "vector->list" "vector-fill!"  "vector-length"
   "vector-move-left!"  "vector-move-right!"  "vector-ref"
   "vector-set!"  "vector?"  "version" "wait-condition-variable"
   "waitpid" "weak-key-hash-table?"  "weak-value-hash-table?"
   "weak-vector" "weak-vector?"  "while" "with-error-to-file"
   "with-fluids*" "with-input-from-file" "with-input-from-string"
   "with-mutex" "with-output-to-file" "with-output-to-string"
   "with-traps" "write-char" "write-line" "write-string/partial"
   "xcons" "xsubstring" "yield" "zero?"  "zip"
   ;; variables
   "%guile-build-info" "%load-extensions" "%load-hook" "%load-path"
   "*features*" "after-gc-hook" "char-set:ascii" "char-set:blank"
   "char-set:digit" "char-set:empty" "char-set:full"
   "char-set:graphic" "char-set:hex-digit" "char-set:iso-control"
   "char-set:letter" "char-set:letter+digit" "char-set:lower-case"
   "char-set:printing" "char-set:punctuation" "char-set:symbol"
   "char-set:title-case" "char-set:upper-case" "char-set:whitespace"
   "F_OK" "INADDR_ANY" "INADDR_BROADCAST" "INADDR_LOOPBACK"
   "INADDR_NONE" "internal-time-units-per-second" "O_APPEND" "O_CREAT"
   "O_RDONLY" "O_RDWR" "O_WRONLY" "R_OK" "REG_EXTENDED" "REG_ICASE"
   "REG_NEWLINE" "REG_NOTBOL" "REG_NOTEOL" "scm_after_gc_c_hook"
   "scm_after_gc_hook" "scm_after_sweep_c_hook" "scm_before_gc_c_hook"
   "scm_before_mark_c_hook" "scm_before_sweep_c_hook" "SCM_BOOL_F"
   "SCM_BOOL_T" "SCM_C_HOOK_AND" "SCM_C_HOOK_NORMAL" "SCM_C_HOOK_OR"
   "SCM_UNDEFINED" "SCM_UNSPECIFIED" "SEEK_CUR" "SEEK_END" "SEEK_SET"
   "SIGHUP" "SIGINT" "W_OK" "WNOHANG" "WUNTRACED" "X_OK"))

(provide 'scheme-lookup-guile)
